### ISSUE TITLE
Error while installing cryptograhpy-1.4 

### ISSUE THREAD

**Issue by ganeshaf** [pyca/cryptography#3044] opened 2016-07-17 07:07 UTC
Hello..I'm trying to set up this for a while..Below is the error it is throwing while installing.
```
sdld0268:~/test/cryptography-1.4 # python3 setup.py install
running install
running bdist_egg
running egg_info
writing src/cryptography.egg-info/PKG-INFO
writing dependency_links to src/cryptography.egg-info/dependency_links.txt
writing requirements to src/cryptography.egg-info/requires.txt
writing entry points to src/cryptography.egg-info/entry_points.txt
writing top-level names to src/cryptography.egg-info/top_level.txt
reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'docs/_build'
warning: no previously-included files matching '*' found under directory 'vectors'
writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
generating cffi module 'build/temp.linux-x86_64-3.5/_padding.c'
already up-to-date
generating cffi module 'build/temp.linux-x86_64-3.5/_constant_time.c'
already up-to-date
generating cffi module 'build/temp.linux-x86_64-3.5/_openssl.c'
already up-to-date
building '_openssl' extension
gcc -pthread -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include/python3.5m -c build/temp.linux-x86_64-3.5/_openssl.c -o build/temp.linux-x86_64-3.5/build/temp.linux-x86_64-3.5/_openssl.o
build/temp.linux-x86_64-3.5/_openssl.c: In function ‘_cffi_const_CMS_DEBUG_DECRYPT’:
build/temp.linux-x86_64-3.5/_openssl.c:7619: error: ‘CMS_DEBUG_DECRYPT’ undeclared (first use in this function)
build/temp.linux-x86_64-3.5/_openssl.c:7619: error: (Each undeclared identifier is reported only once
build/temp.linux-x86_64-3.5/_openssl.c:7619: error: for each function it appears in.)
error: command 'gcc' failed with exit status 1
```
Can somebody please help

**Comment by reaperhulk** [comment] 2016-07-17 12:58
Could you give us some details about your environment? What distribution of linux are you running? What's the output of `openssl version`? Have you installed a custom version of openssl/libressl?

**Comment by ganeshaf** [comment] 2016-07-18 05:28
Below are the details

sdld0268:~/test/cryptography-1.4 # cat /etc/issue

Welcome to SUSE Linux Enterprise Server 11 SP1  (x86_64) - Kernel \r (\l).

sdld0268:~/test/cryptography-1.4 # openssl version
OpenSSL 0.9.8h 28 May 2008

Other packages installed are
sdld0268:~/test/cryptography-1.4 # rpm -qa | grep -i openssl
libopenssl0_9_8-0.9.8h-30.27.11
libopenssl0_9_8-32bit-0.9.8h-30.27.11
openssl-0.9.8h-30.27.11
openssl-certs-0.9.8h-27.1.30
libopenssl-devel-1.0.0c-17.1
libopenssl1_0_0-1.0.0c-17.1

**Comment by alex** [comment] 2016-07-22 00:57
This looks like you have multiple OpenSSLs installed. Further, it looks like your current OpenSSL is 0.9.8, which cryptography does not support. You should make sure you're linking clearly against a supported OpenSSL (I note that your other OpenSSL is 1.0.0, which we do currently support, but will be dropping in the future).

I'm going to close this for now; if you're still able to reproduce, please provide clear instructions which we can use to reproduce.

**Closed by alex** 2016-07-22 00:57 UTC
