### ISSUE TITLE
please add OpenBSD 6.1 with LibreSSL to supported platforms

### ISSUE THREAD

**Issue by plavcik** [pyca/cryptography#3855] opened 2017-08-09 08:00 UTC
https://cryptography.io/en/latest/installation/#supported-platforms

with these instruction

pkg_add llvm
CC=clang pip install cryptography

thank you

**Comment by alex** [comment] 2017-08-09 11:06
Closing as a duplicate of #3854

**Closed by alex** 2017-08-09 11:06 UTC
