### ISSUE TITLE
Why doesn't the random numbers doc page mention SystemRandom?

### ISSUE THREAD

**Issue by bjmc** [pyca/cryptography#3470] opened 2017-03-21 13:39 UTC
The [documentation about random number generation](https://cryptography.io/en/latest/random-numbers/) points out that the default `random` module is insecure for cryptographic uses, and suggests using `os.urandom()` instead, but it makes no mention of the [`SystemRandom()`](https://docs.python.org/2.7/library/random.html#random.SystemRandom) class. According to the Python documentation, `SystemRandom()` specifically addresses this use case by using `os.urandom()` internally, while presenting the same interface as the default `random`.

Is `SystemRandom()` considered flawed in some way? If not, should it be mentioned on the random numbers doc page?

**Comment by alex** [comment] 2017-03-21 13:40
Closing as a dupe of #2278, #2410. Hopefully the discussions there fully explain our decision, if not leave a comment and we can reopen.

**Closed by alex** 2017-03-21 13:40 UTC
