### ISSUE TITLE
Ed25519 OpenSSH serialization not supported

### ISSUE THREAD

**Issue by akx** [pyca/cryptography#4824] opened 2019-03-29 14:22 UTC
#4785 implemented deserialization of SSH ed25519 public keys, but serializing them back into the same format is not supported.

```python
>>> import cryptography.hazmat.primitives.asymmetric.ed25519 as e
>>> from cryptography.hazmat.primitives import serialization
>>> key = e.Ed25519PrivateKey.generate()
>>> public_key = key.public_key()
>>> public_key.public_bytes(
...     encoding=serialization.Encoding.OpenSSH,
...     format=serialization.PublicFormat.OpenSSH,
... )
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "cryptography/hazmat/backends/openssl/ed25519.py", line 45, in public_bytes
    encoding, format, self, self._evp_pkey, None
  File "cryptography/hazmat/backends/openssl/backend.py", line 1838, in _public_key_bytes
    return self._openssh_public_key_bytes(key)
  File "cryptography/hazmat/backends/openssl/backend.py", line 1886, in _openssh_public_key_bytes
    assert isinstance(key, ec.EllipticCurvePublicKey)
AssertionError
```

* Python 3.7.2
* cryptography 2.6.1
* cffi 1.12.2

**Comment by alex** [comment] 2019-03-29 14:26
Dupe of #4808 -- this will be in our next release.

**Comment by akx** [comment] 2019-03-29 14:26
Ah, cheers. Sorry for the duplicate!

**Closed by alex** 2019-03-29 14:26 UTC
