### ISSUE TITLE
PyO3 error

### ISSUE THREAD

**Issue by LukasJerabek** [pyca/cryptography#9719] opened 2023-10-13 12:19 UTC
I had to downgrade back to 40.0.2 version because in newer versions I got these errors when running tests with pytest. Is PyO3 some dependency? What could be the problem? Dunno how make newer versions work.

```
   BROKEN  .tests.integ.iadmin.modules.use_cases.test_aggregated_payments
ImportError while importing test module '/home/vagrant/pack/tests/integ/iadmin/modules/use_cases/test_aggregated_payments.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../.pyenv/versions/3.8.18/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/integ/iadmin/modules/use_cases/test_aggregated_payments.py:7: in <module>
    from iadmin.modules.use_cases.aggregated_payments import (
iadmin/modules/use_cases/aggregated_payments.py:5: in <module>
    from aukce.modules.auction import Auction as LegacyAuction
aukce/modules/auction.py:10: in <module>
    from shared_globals.modules.legacy_document import Document
shared_globals/modules/legacy_document.py:17: in <module>
    from shared_globals.use_cases.invoice_status import add_new_invoice_statuses
shared_globals/use_cases/invoice_status.py:3: in <module>
    from shared_globals.celery.hooks_tasks.notify_invoice_status_hooks import (
shared_globals/celery/hooks_tasks/notify_invoice_status_hooks.py:1: in <module>
    from partner_api.modules.use_cases.hooks import (
partner_api/modules/use_cases/hooks.py:8: in <module>
    from shared_globals.use_cases.hooks import (
shared_globals/use_cases/hooks.py:11: in <module>
    from shared_globals.jws_security import generate_jws
shared_globals/jws_security.py:4: in <module>
    from cryptography.hazmat.primitives import hashes
../venv/pack/lib/python3.8/site-packages/cryptography/hazmat/primitives/hashes.py:10: in <module>
    from cryptography.hazmat.bindings._rust import openssl as rust_openssl
E   ImportError: PyO3 modules may only be initialized once per interpreter process
```

**Comment by alex** [comment] 2023-10-13 12:24
Are you able to reproduce this if you install from git? I think this may have been fixed by https://github.com/PyO3/pyo3/pull/3446, which was just incorporated yesterday.

**Comment by LukasJerabek** [comment] 2023-10-13 15:45
I have centos7, I have installed Rust, cargo and newer openssl version according to:
`https://gist.github.com/Bill-tran/5e2ab062a9028bf693c934146249e68c`

I am trying with:
```
pip install git+https://github.com/pyca/cryptography.git
```

but I now get:
```
   BROKEN  .tests.unit.iadmin.modules.adapters.form.test_edit_invoice
ImportError while importing test module '/home/vagrant/pack/tests/unit/iadmin/modules/adapters/form/test_edit_invoice.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../.pyenv/versions/3.8.18/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
.
.
.
    from cryptography.hazmat.primitives import hashes
../venv/pack/lib/python3.8/site-packages/cryptography/hazmat/primitives/hashes.py:9: in <module>
    from cryptography.hazmat.bindings._rust import openssl as rust_openssl
E   ImportError: /home/vagrant/venv/pack/lib/python3.8/site-packages/cryptography/hazmat/bindings/_rust.abi3.so: undefined symbol: DSA_set0_key
```

So I am not sure if I installed it right...

**Comment by LukasJerabek** [comment] 2023-10-13 15:52
Btw when I installed the pip package I have got confirmation:
Successfully installed cryptography-42.0.0.dev1

**Comment by LukasJerabek** [comment] 2023-10-16 14:36
However my suspicion has turned to python-cov package now. In case you are interested, since I am still not sure, which package exactly causes it (python-cov or both jsonschema and cryptography), you can check out the reproducer here https://github.com/pytest-dev/pytest-cov/issues/614.

**Comment by alex** [comment] 2023-10-16 14:37
We use `pytest-cov` in our own tests, so I doubt that. However, do you have other pytest plugins that may be involved?

**Comment by LukasJerabek** [comment] 2023-10-16 14:42
Just pytest-cov

**Comment by alex** [comment] 2023-11-01 17:57
I believe this is a duplicate of https://github.com/pyca/cryptography/issues/9016

**Closed by alex** 2023-11-01 17:57 UTC
