### ISSUE TITLE
ValueError: error parsing asn1 value: ParseError when handling Cert with Unicode Chars

### ISSUE THREAD

**Issue by BeryJu** [pyca/cryptography#6804] opened 2022-01-10 19:28 UTC
Source issue: https://github.com/goauthentik/authentik/issues/2082

When loading a certificate with Umlauts in issuer and subject, and attempting to do anything with it, an error is raised.

Expected values from `openssl x509 -in cert.pem -text -noout`:
```
[...]
        Issuer: CN=Internal-CA, C=FR, ST=Auvergne-Rh\xF4ne-Alpes, L=Saint-Marcellin, O=Giordana Home
        Validity
            Not Before: Jan  9 22:42:51 2022 GMT
            Not After : Jan 11 22:42:51 2023 GMT
        Subject: CN=authentik.company, C=FR, ST=Unicode \xF4, L=city, O=org
[...]
```

When loading with cryptography (all versions should be visible below):

```
❯ docker run -it --rm --entrypoint /bin/bash docker.io/python:3.10.1-slim-bullseye
root@7251b805458d:/# pip install -U pip setuptools
Requirement already satisfied: pip in /usr/local/lib/python3.10/site-packages (21.2.4)
Collecting pip
  Downloading pip-21.3.1-py3-none-any.whl (1.7 MB)
     |████████████████████████████████| 1.7 MB 2.8 MB/s
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/site-packages (57.5.0)
Collecting setuptools
  Downloading setuptools-60.5.0-py3-none-any.whl (958 kB)
     |████████████████████████████████| 958 kB 5.6 MB/s
Installing collected packages: setuptools, pip
  Attempting uninstall: setuptools
    Found existing installation: setuptools 57.5.0
    Uninstalling setuptools-57.5.0:
      Successfully uninstalled setuptools-57.5.0
  Attempting uninstall: pip
    Found existing installation: pip 21.2.4
    Uninstalling pip-21.2.4:
      Successfully uninstalled pip-21.2.4
Successfully installed pip-21.3.1 setuptools-60.5.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@7251b805458d:/# pip install cryptography
Collecting cryptography
  Downloading cryptography-36.0.1-cp36-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.manylinux_2_24_aarch64.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 3.0 MB/s
Collecting cffi>=1.12
  Downloading cffi-1.15.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (448 kB)
     |████████████████████████████████| 448 kB 7.5 MB/s
Collecting pycparser
  Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
     |████████████████████████████████| 118 kB 6.5 MB/s
Installing collected packages: pycparser, cffi, cryptography
Successfully installed cffi-1.15.0 cryptography-36.0.1 pycparser-2.21
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@7251b805458d:/# python
Python 3.10.1 (main, Dec 21 2021, 06:25:50) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> cert = """-----BEGIN CERTIFICATE-----
... MIIFtjCCA56gAwIBAgIBGzANBgkqhkiG9w0BAQsFADB0MRQwEgYDVQQDEwtJbnRl
... cm5hbC1DQTELMAkGA1UEBhMCRlIxHTAbBgNVBAgUFEF1dmVyZ25lLVJo9G5lLUFs
... cGVzMRgwFgYDVQQHEw9TYWludC1NYXJjZWxsaW4xFjAUBgNVBAoTDUdpb3JkYW5h
... IEhvbWUwHhcNMjIwMTA5MjI0MjUxWhcNMjMwMTExMjI0MjUxWjBaMRowGAYDVQQD
... ExFhdXRoZW50aWsuY29tcGFueTELMAkGA1UEBhMCRlIxEjAQBgNVBAgUCVVuaWNv
... ZGUg9DENMAsGA1UEBxMEY2l0eTEMMAoGA1UEChMDb3JnMIIBIjANBgkqhkiG9w0B
... AQEFAAOCAQ8AMIIBCgKCAQEAxj9t6OM7y5hbpnhxhUVh8A0yXNB7v8kx2Bb/dC32
... QBSJGNXG2p0bYfOc4dlQj6Es4ocrqZchxnwRblgmhknomCwPlPUsXGqW+7/pUGf6
... CyZYroQdLLX8KzdrrPFNljBkuxBgH+3D2G367C6GWPIvOY2jalgAs7lKY3UnsuEg
... utSmcFss+TnkkMFtrBTQNVEZsHIAer9QUcMI07R0OrRh/iaEBc8LEKTvBBYKKtsT
... JFMcU5M1DeLS4VoQpHMmtFw0rZZGZhUV0G+alNqUFHKDXZeZoMlzZqsGEZdgxAYa
... rUFAvLN44E42LbpheuX7/2TNeL84VZ508hF7hKv8WXN37wIDAQABo4IBazCCAWcw
... CQYDVR0TBAIwADARBglghkgBhvhCAQEEBAMCBkAwCwYDVR0PBAQDAgWgMDMGCWCG
... SAGG+EIBDQQmFiRPcGVuU1NMIEdlbmVyYXRlZCBTZXJ2ZXIgQ2VydGlmaWNhdGUw
... HQYDVR0OBBYEFKgMqYm+NouE7fkE1Wl/KuXIXm/5MIGeBgNVHSMEgZYwgZOAFJsm
... iWncuuPunTPxo8BPisp8XrvmoXikdjB0MRQwEgYDVQQDEwtJbnRlcm5hbC1DQTEL
... MAkGA1UEBhMCRlIxHTAbBgNVBAgUFEF1dmVyZ25lLVJo9G5lLUFscGVzMRgwFgYD
... VQQHEw9TYWludC1NYXJjZWxsaW4xFjAUBgNVBAoTDUdpb3JkYW5hIEhvbWWCAQAw
... JwYDVR0lBCAwHgYIKwYBBQUHAwEGCCsGAQUFBwMCBggrBgEFBQgCAjAcBgNVHREE
... FTATghFhdXRoZW50aWsuY29tcGFueTANBgkqhkiG9w0BAQsFAAOCAgEAHZjk6KrP
... 744Xlk8ykreJ4fiQE9EiVgR8aoE7eKk21xX3HJaeU2fq9voxTn85drGUMNlG7NrR
... CNaiAZCwqEy7fV264QRLCOz7p0hx7x4eDQnFd2PuQNstB34jzR8UBHVPREkxdGn8
... QNxN9i4CMOT2oc0mpF6+gWdf/y1a3VgbAgvvVLa27bkkCjSy5HIyErrZG2Qt+hmf
... EvMH1u4lQgffLbDhWeWNd7qFG+zKp78VAvZxbVEjEfMhWbTXz1iIzXY+Anq6mOP2
... K/I8xF6urlnBCSmVgaeMoXKZnFq5FGxC9sSyp6TP8GnTsy5+zP9lZFLpFdnh7fw5
... xc06Uz2Gj6gZnogngh1eVOeS92LRuUP32kb2m+DNPSkBH4+5EIC90c21GcDEpS1U
... DVlSJe3m0yS+3SXWNp8U/M0UYTMEwDGW5KR0y3PJ5YM32jW0TErO25DteA1fe7VS
... 9mD3+2cPwrbaPXH6vhNBi5xzZnsiAeOP6Wx4hbElviHWVee00kD5+FnUBp7FMq4E
... iryTkKlMbqVJLTs4H6sc5Ov2BRCcAa/3RuPhkK+apQz6VyTZLoePz5nVvUdF7mvg
... LSgCKfDU2kNCMas0OzuZk145WxAnAl2ZTty2PyqgK2Hfeill++j31Of9voUQLCIe
... iNBmQCLvdE1eBC8zsGsZbG2D4/IlOoRDnkw=
... -----END CERTIFICATE-----
... """
>>> from cryptography.x509 import load_pem_x509_certificate
>>> from cryptography.hazmat.backends import default_backend
>>>
>>> load_pem_x509_certificate(cert.encode(), default_backend())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: error parsing asn1 value: ParseError { kind: InvalidValue }
>>>
```

Mind you, after some more testing, I can successfully load the certificate when I assign it to a variable, but afterwards calling anything on that variable will cause the same error.

**Comment by reaperhulk** [comment] 2022-01-10 20:10
This is occurring because the value for the OID 2.5.4.8 (stateOrProvinceName) doesn't contain valid unicode at all. `\xf4` is not a valid unicode character. Based on context it looks like there's an expectation that this encodes ô, but that is encoded as `\x00\xf4` in utf16 and `\xc3\xb4` in utf8. Our API requires that values by representable as python strings and so our parser decodes assuming utf8 (except in specific cases where we know that the underlying ASN.1 string type guarantees utf16 or utf32).

This certificate is definitely invalid (and the reason you're seeing it fail in your example is because our `__repr__` parses subject/issuer which immediately triggers the exception), but we'd like to know a bit more about where you're seeing these and what's generating this type of invalid encoding if you can share.

**Comment by BeryJu** [comment] 2022-01-10 20:26
Not my certificate, @danaelg reported the issue to me since this certificate breaks authentik which uses cryptography (see https://github.com/goauthentik/authentik/issues/2082), maybe they can give some light on what they used to generate the certificate.

**Comment by danaelg** [comment] 2022-01-10 20:31
Very interresting !
It was generated using pfsense cert manager (v2.5.2).

**Comment by alex** [comment] 2022-01-10 20:43
Notably \xF4 is how you'd encode this character in latin-1. It sounds like pfsense is not handling unicode correctly. I don't actually have a pfsense myself, if someone here does have one it'd be good if we could definitely prove this and file a bug with them.

**Comment by danaelg** [comment] 2022-01-11 08:12
As for now I'm the only one concerned by this bug, I'll open an issue in pfsense bug tracker. I'll give them the information you all provided in this issue.

Thanks.

**Comment by alex** [comment] 2022-01-12 01:06
Please share a link when you do file it!

**Comment by danaelg** [comment] 2022-01-12 07:24
I create a post on reddit /r/PFSENSE before creating an issue in their bug tracker (this is what they recommand) and a user sent me the link to an already opened issue that I had not found: https://redmine.pfsense.org/issues/12035.

This issue will be resolve in the next release coming early 2022.

reddit post : https://www.reddit.com/r/PFSENSE/comments/s1mn2g/cert_manager_doesnt_handle_utf8/

**Comment by danaelg** [comment] 2022-01-12 14:36
I've tested the beta of the next release. I can confirm it's resolved. they actually prevent the use of UTF-8 char (that's a way of doing...).

I think we can close this issue.

Thanks again for your light !

**Comment by alex** [comment] 2022-01-12 14:41
I'm actually going to hold this open: I'd like us to improve the error message that one gets here to include which field is invalid so folks have an easier time debugging.

**Closed** 2022-02-07 03:42 UTC
Labels: x509

**Comment by kaimast** [comment] 2022-02-11 05:44
> I'm actually going to hold this open: I'd like us to improve the error message that one gets here to include which field is invalid so folks have an easier time debugging.

I'm trying to debug a similar issue. The error message I now get is the following:

```
 ParseError { kind: InvalidValue, location: ["0", "AccessDescription::access_method"] }
```

Not sure which field it could refer to. Any thoughts on what could cause an error like this?

**Comment by reaperhulk** [comment] 2022-02-11 05:48
AccessDescription is within a SubjectInformationAccess or (much more likely) AuthorityInformationAccess extension (typically used for OCSP URIs). The access_method is an ObjectIdentifier defining the type of access method encoded. This suggests you appear to have a cert with an invalid OID encoded. Is this something you can share?

**Comment by kaimast** [comment] 2022-03-02 01:35
Sorry for commenting on this somewhat unrelated issue.

I noticed that the OID above contains a rather large integer. Looking at the `asn1` crate it seems like it does not support anything greater than 32bits.
(See here: https://github.com/alex/rust-asn1/blob/68695c805ee44c33c91bb1169b613c34a7ad6d60/src/object_identifier.rs#L59)

Is the OID in my certificate even valid? If so, `asn1` probably needs to be patched to support larger numbers in OIDs.

**Comment by alex** [comment] 2022-03-02 01:39
Discussed in https://github.com/pyca/cryptography/issues/6573
