### ISSUE TITLE
Add support for MGF1 hashes

### ISSUE THREAD

**Issue by harmin-parra** [pyca/cryptography#7331] opened 2022-06-13 04:02 UTC
Add support for RSA-SSA-PSS related hashes

I get this error when parsing a certificate

```
print(cert.signature_hash_algorithm)
cryptography.exceptions.UnsupportedAlgorithm: Signature algorithm OID: 1.2.840.113549.1.1.10 not recognized
```

The certificate:

```
-----BEGIN CERTIFICATE-----
MIIEnTCCAtGgAwIBAgIUarIN27uqpOjJb0ylPcVFY4Et6CcwQQYJKoZIhvcNAQEK
MDSgDzANBglghkgBZQMEAgEFAKEcMBoGCSqGSIb3DQEBCDANBglghkgBZQMEAgEF
AKIDAgEgMBkxFzAVBgNVBAMMDlJTQS1TU0EtUFNTIENBMB4XDTIyMDYwMjA5MDEz
MloXDTIzMDYwMjA5MDEzMlowJzEPMA0GA1UECgwGSUQgUEtJMRQwEgYDVQQDDAty
c2Egc3NhIHBzczCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBALS7KcOY
af9SBqGfI7wTig+yvQ+BxM/cyCF8wAo6B9ktqutVhZdZJcyEtplbhSQlzlCeOmdh
dekuQRTOfhZ9v9Y9Wxp3gem70qortsNJ7hRou/o7V0mz3tudp5lNvSbnoAb1/zwW
94eskSYWw/O0xW+2A40pFu/UBA7nu6BsM0TfYbJIXvyBoDXmWCw8fH7eNrtobjXo
6qSpc75EkO3xQVQda2BfZ0VNR49C6Vo3/kB848pozUJj5KDVOemTnuQscS0DiSrn
Xppii8UmlwU1p7ApPdZOuueFNKtuVEYIQ/8ZvfALSHIUpyb+GyJNHxRoSpQ6LWbd
+46NwtE2kKpMAENGutMuSQKb1hJ+JcQ/HEeoxrIaGGXFMfLETIBNl7RnSyFoEq+y
24coc5ai0Qjfnvoom7e4W3UODpxxLTrFabCIKS4dYCtVITwXTnYSBGYh756BOD2f
I7TOB1CuuzP22BgOviPxahJNh4/B4aUX86gvv8lUN/Kjl0FdzxVT7YFtmwIDAQAB
o2cwZTAdBgNVHQ4EFgQU8KeGPRPCWvu1yQDjqYkjqW3Bl8EwHwYDVR0jBBgwFoAU
xEIyqAAtOuNzOs8VqOJwsYiqA9AwDgYDVR0PAQH/BAQDAgeAMBMGA1UdJQQMMAoG
CCsGAQUFBwMCMEEGCSqGSIb3DQEBCjA0oA8wDQYJYIZIAWUDBAIBBQChHDAaBgkq
hkiG9w0BAQgwDQYJYIZIAWUDBAIBBQCiAwIBIAOCAYEAC/KQHkPTivNZKMoHov0V
rJqU643Kd8xwK2pttWauhlHAQU7wuHzYRMZFL5gjw2epuTq0J6mtzKKcsGS94Hwq
fF/g8fQSoKC7c0QSZpVlyzM8DcZSXU6F0O3vZo3Do/tNvLxf4f02HMJ5HcuUALOR
QblV6IK8r50hSYA/YBnLP1swV+yF6Aw86rRYVKKpXQWFHTXbXA19A1Yb2Yc6rJiA
Goh8bsjmo1egsmdf9io1Ec9l75EPwNiPphp9fW9SdGpZDuG327+y98ehzGEhqtiA
wrUoD1Y7XrLlbsc1cMYvilzRfVCr+q1vxGDXZeEMgYCbG31M9Cl4VK3gMkORnOZ3
eExY4liVzrmUZr52tHxpMC9MGxiyUIYGcJEkAFirIwnGFmft31cjAzfh1bzW0EcL
VB1gSeRiXp0nbHoXU+rGg4o01Ipn2elLgY+zb513LLeW3CpdoOx5Z12rYtj4YKnz
GTG83mu2GBAYDRMOSNfIw3ZhcuJhlHaaGr5F/OPUm9wp
-----END CERTIFICATE-----
```

**Comment by reaperhulk** [comment] 2022-06-13 07:38
Duplicate of #2850

**Closed by reaperhulk** 2022-06-13 07:38 UTC
