### ISSUE TITLE
Removing RSA keys from memory when no longer needed

### ISSUE THREAD

**Issue by SirCmpwn** [pyca/cryptography#2695] opened 2016-01-28 22:11 UTC
Is there/can there be a way to do this?

**Comment by reaperhulk** [comment] 2016-01-28 22:33
There's no way to zero memory if it has been loaded into a Python string or int. Unfortunately since you have to load the serialized key and (if required) a password with our current API there's therefore no way to do it. 

It is feasible to use only C functions to load a key so that all memory can be safely zeroed, but what that API would look like (or whether we'd want to support two loading APIs) is undetermined.

**Comment by SirCmpwn** [comment] 2016-01-28 22:41
Perhaps providing new string/int-like primitives in cryptography that are backed by native code would be a good solution. These could be the inputs to functions that need secrets (which could accept both python strings and cryptography strings, so no API change is necessary), and could offer functions to securely erase them.

**Comment by alex** [comment] 2016-02-05 02:33
The problem is how do you get an instance of these primitives? If the value was _ever_ in a `str`, then you don't get the benefits of this. That means you can never `file.read()` or get a value out of `dataReceived` in twisted, or `requests.get()`, the list goes on. While it's a good idea, I don't think it's practical.

**Comment by SirCmpwn** [comment] 2016-02-05 02:35
It's not that complex. Just pass a filename instead of the actual key string, then cryptography does the dirty work of going out to native code to read the file and load the key, and returns a handle for that key. Honestly this will fulfil a good 90% of use cases, minimum.

**Comment by reaperhulk** [comment] 2016-02-14 02:32
I don't see a good API for this right now. It's easy to say just make it `serialization.load_pem_private_key_from_file` but then it also has a note that says this one has special memory characteristics vs `load_pem_private_key`? But you lose those if you call `private_bytes` (so you'd need something like `private_bytes_to_file` maybe)? That's going to create a lot of questions from users.

Key handles might solve this issue in a reasonable fashion in the future, but for now I don't see a way to do this without significantly complicating the API.

**Comment by alex** [comment] 2016-03-06 15:14
Going to close this, as I believe it's impractical to do in Python without re-doing all file IO APIs.

**Closed by alex** 2016-03-06 15:14 UTC
