### ISSUE TITLE
"is" test of exceptions._Reasons value not working in Fedora Rawhide

### ISSUE THREAD

**Issue by pghmcfc** [pyca/cryptography#11332] opened 2024-07-22 14:01 UTC
In the last few days there has been a mass rebuild of all packages in the Fedora Linux development branch as part of the upcoming Fedora 41 release. Fedora 41 currently has Python 3.13.0b3, pytest-7.4.3 and cryptography 42.0.8.

One of the packages, python-paramiko, which uses cryptography internally, failed to build successfully due to a number of test cases failing with the error `cryptography.exceptions.UnsupportedAlgorithm: sha1 is not supported by
this backend for RSA signing.` It was not unexpected that SHA1 signing support was not available: what was unexpected was that the test suite failed as a result of this. There has been support in paramiko's test suite since 2022 for running with an OpenSSL built without SHA1 signing, skipping the tests that are known to fail in that case. What happened here was that the test skipping did not happen. After some debugging, the cause seems to be the way that the lack of SHA1 signing support is detected.

The paramiko test suite has this function in `tests/_util.py`:
```
def sha1_signing_unsupported():
    """
    This is used to skip tests in environments where SHA-1 signing is
    not supported by the backend.
    """
    private_key = rsa.generate_private_key(
        public_exponent=65537, key_size=2048, backend=default_backend()
    )
    message = b"Some dummy text"
    try:
        private_key.sign(
            message,
            padding.PSS(
                mgf=padding.MGF1(hashes.SHA1()),
                salt_length=padding.PSS.MAX_LENGTH,
            ),
            hashes.SHA1(),
        )
        return False
    except UnsupportedAlgorithm as e:
        return e._reason is _Reasons.UNSUPPORTED_HASH
```
This function worked almost exactly as intended, with the signing attempt raising an `exceptions.UnsupportedAlgorithm` exception with `_reason` being `_Reasons.UNSUPPORTED_HASH`. However, the test still failed because the `is` check on the last line returned `False`. If I changed the test to use `==` instead of `is` then it worked as expected.

The test was written to use `is` because `_Reasons` is an enum, which should be a singleton, and the Python documentation says that the identity comparison is the right thing to do (https://docs.python.org/3/howto/enum.html#comparisons). Moreover, cryptography's own test suite does a similar test:
```
@contextmanager
def raises_unsupported_algorithm(reason):
    with pytest.raises(UnsupportedAlgorithm) as exc_info:
        yield exc_info

    assert exc_info.value._reason is reason
```
which is called like this (from `tests/hazmat/primitives/test_rsa.py`):
```
        with raises_unsupported_algorithm(_Reasons.UNSUPPORTED_HASH):
            private_key.sign(message, pss, hashes.BLAKE2s(32))
```
So my question is: is this a bug in paramiko, in cryptography, or a regression in Python itself? I tried asking on the Fedora devel list (https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/QGTKQX77CJEEGENNMAT65XZAZRQX44KL/) and there wasn't a conclusive answer, the suggestion being that I should raise the issue here.

Obviously I can get this working by changing the `is` to `==` but if there is an actual Python bug here, it would be best to know before 3.13 comes out of beta.

**Comment by alex** [comment] 2024-07-22 14:13
I'll start with `_Reasons` is not a public API (hence the leading underscore), so we don't commit to any particular backwards compatibility policy for it.

The underlying change here is likely that we moved `_Reasons` to Rust, where enums are unfortunately not-yet singletons (see https://github.com/PyO3/pyo3/issues/3059). In the short term, `==` is the right fix. In the long term once that pyo3 issue is resolved, then comparison by identity will work.

**Comment by pghmcfc** [comment] 2024-07-22 14:30
Ok, thanks for the feedback. I'll make that change. I guess it's possible that cryptography's own test suite may hit the same issue at some point then since it also uses an identity comparison.

Regarding the private API, do you have any suggestions for determining whether SHA1 signing support is available using only the public API? I guess I could not test the `_reason` value but that might then lead to the tests being skipped due to some other issue, which wouldn't be good.

**Comment by alex** [comment] 2024-07-22 14:32
Yes, it's possible we'll also hit this, but we're allowed to depend on our own implementation details 😂.

In theory we're ok with SHA1 signature support being a public API, however, the problem is that Red Hat's OpenSSL patches don't actually provide any public API to introspect whether they're supported.

**Comment by pghmcfc** [comment] 2024-07-22 14:34
Indeed, that's why I had to write that test function in the first place for paramiko.

**Comment by alex** [comment] 2024-07-22 14:36
For our own tests, we just gave up and set the `OPENSSL_ENABLE_SHA1_SIGNATURES` environment variable.

**Comment by alex** [comment] 2024-07-22 20:22
I see the PR was sent to paramiko, so I'm going to close this. Thanks.

**Closed by alex** 2024-07-22 20:22 UTC
