### ISSUE TITLE
Building wheel for cryptography (pyproject.toml) takes forever

### ISSUE THREAD

**Issue by notacodingweeb** [pyca/cryptography#7905] opened 2022-12-17 19:52 UTC
Hi im pretty new to this. I am installing firebase_admin using pip. It was going well until building wheel for cryptography. It doesnt show any error whatsoever but I have been waiting for more than 20 mins. Is it normal? Is there something that i missed? I would appreciate your help. 

![image](https://user-images.githubusercontent.com/100553943/208263751-775ea4d5-11eb-40db-9cd6-3fd69c14f78e.jpg)

**Comment by alex** [comment] 2022-12-18 02:29
If you are on a low-powered device, particularly low RAM, compilation can take long time due to swapping.

The fix for that is generally to use a pre-built wheel. piwheels ordinarily has them for cryptography, but unfortunately due to https://github.com/piwheels/piwheels/pull/328 they don't have wheels for recent versions of cryptography.

I'm going to close this as a dupe of #7636, since its the same root cause. But if there's more here, leave a comment and we can reopen.

**Closed by alex** 2022-12-18 02:29 UTC

**Comment by notacodingweeb** [comment] 2022-12-18 07:31
I left it overnight and it works. Thank you!
