### ISSUE TITLE
Failing to install cryptography 2.1.1 on python 2.7.6

### ISSUE THREAD

**Issue by anderstheet** [pyca/cryptography#3976] opened 2017-10-12 08:27 UTC
Unable to install the newest version of cryptography.

It's on a freshly install ubuntu trusty with python 2.7.6.
I have installed these packages: python-pip python2.7-dev build-essential libssl-dev libffi-dev python-dev postgresql postgresql-server-dev-9.3 libyaml-dev libpython2.7-dev libsasl2-dev libldap2-dev postgresql-contrib

Here is my output:
```app@cc91312f0d77:/app$ pip install cryptography
Downloading/unpacking cryptography
  Downloading cryptography-2.1.1.tar.gz (441kB): 441kB downloaded
  Running setup.py (path:/tmp/pip_build_app/cryptography/setup.py) egg_info for package cryptography
    error in cryptography setup command: Invalid environment marker: python_version < '3'
    Complete output from command python setup.py egg_info:
    error in cryptography setup command: Invalid environment marker: python_version < '3'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_app/cryptography
Storing debug log for failure in /home/app/.pip/pip.log

**Comment by reaperhulk** [comment] 2017-10-12 08:31
Try upgrading your pip and setuptools (the error indicates these packages are out of date and don't support environment markers). I'm going to close this but please comment again if this doesn't fix it.

**Closed by reaperhulk** 2017-10-12 08:31 UTC

**Comment by eastokes** [comment] 2017-10-13 00:27
Same error here. I've reverted back to 2.0.3
`pip 9.0.1
setuptools 36.6.0`

**Comment by reaperhulk** [comment] 2017-10-13 00:29
If you're seeing the `python_version` invalid marker warning you probably have a copy of a very old setuptools living somewhere on your system that is being improperly loaded. To confirm try creating a virtualenv (using the latest virtualenv so it installs the latest pip/setuptools properly) and installing into that. If that works then the issue is with your global environment.

**Comment by yozik04** [comment] 2017-10-13 11:12
I've debugged this half a day today. Cleared all setuptools and pip installations. Still no luck.

pip 9.0.1
setuptools 36.6.0

Can't install cryptography 2.1.1.

`Downloading/unpacking cryptography (from azure-storage>=0.31.0,<1.0.0->-r ./requirements.txt (line 9))
  Using version 2.1.1 (newest of versions: 2.1.1, 2.1, 2.0.3, 2.0.2, 2.0.1, 2.0, 1.9, 1.8.2, 1.8.1, 1.8, 1.7.2, 1.7.1, 1.7, 1.6, 1.5.3, 1.5.2, 1.5.1, 1.5, 1.4, 1.3.4, 1.3.3, 1.3.2, 1.3.1, 1.3, 1.2.3, 1.2.2, 1.2.1, 1.2, 1.1.2, 1.1.1, 1.1, 1.0.2, 1.0.1, 1.0, 0.9.3, 0.9.2, 0.9.1, 0.9, 0.8.2, 0.8.1, 0.8, 0.7.2, 0.7.1, 0.7, 0.6.1, 0.6, 0.5.4, 0.5.3, 0.5.2, 0.5.1, 0.5, 0.4, 0.3, 0.2.2, 0.2.1, 0.2, 0.1)
  Downloading from URL https://pypi.python.org/packages/bf/da/6a9f49cc7a970380c8235b3adab0c08c7c3d4814876f7383b33e3882a577/cryptography-2.1.1.tar.gz#md5=fa98118b468020349a798776aac6d572 (from https://pypi.python.org/simple/cryptography/)
  Running setup.py (path:/tmp/pip-build-E567LO/cryptography/setup.py) egg_info for package cryptography
    error in cryptography setup command: Invalid environment marker: python_version < '3'
    Complete output from command python setup.py egg_info:
    error in cryptography setup command: Invalid environment marker: python_version < '3'`

**Comment by rloomba** [comment] 2017-10-17 05:30
>If you're seeing the python_version invalid marker warning you probably have a copy of a very old setuptools living somewhere on your system that is being improperly loaded

@reaperhulk I'm actually having the same problem, and I've tried updating packages on my base trusty image. I'm using [python-pip](https://packages.ubuntu.com/trusty/python-pip) to manage my pip versions. The most updated version of pip that comes with trusty is 1.5.4. It would be nice if this package was backwards compatible with a base trusty image.

If you will accept a patch for this change, please let me know and any hints on what in the codebase to change.

**Comment by alex** [comment] 2017-10-17 05:34
We are intentionally using newer features that older pips do not support, so unfortunately this is not an option.

I recommend getting a pip that's not from apt (or finding a backport PPA), as sticking to 1.5 is severely limiting.

**Comment by rloomba** [comment] 2017-10-17 05:54
@alex got it! Appreciate the response.
