### ISSUE TITLE
Adding type hinting for cryptography

### ISSUE THREAD

**Issue by software-opal** [pyca/cryptography#4275] opened 2018-06-07 14:36 UTC
I'm using your library in a code base that uses typechecking and I'd like to be able to perform the type checking on my usage of cryptography.

One way is to add typed stubs of `cryptography` into [typeshed](https://github.com/python/typeshed/).

**Comment by reaperhulk** [comment] 2018-06-07 15:57
We talked with someone at PyCon US this year about type stubs and we decided typeshed was a good place for them to live for now. We're happy for someone to do it, but we have no plans to do it ourselves at this time.

**Comment by jlaine** [comment] 2019-05-13 23:31
If the plan is to provide type annotations in the form of .pyi files, does it matter if the .pyi files "pretend" that we are using subclassing instead of ABC registration?

I have started putting together (partial) stubs to be able to use mypy on one of my projects: https://github.com/aiortc/aioquic/tree/master/stubs/cryptography

**Comment by reaperhulk** [comment] 2019-05-18 12:18
With `pyi` files the problem is that we have to duplicate every ABC with an equivalent protocol and make sure we keep them in sync, correct?

**Comment by jlaine** [comment] 2019-05-22 20:12
I believe so, yes

**Comment by glyph** [comment] 2019-07-29 03:56
Another way to go about this might be to simply replace the ABCs with Protocols completely.  Protocols can be defined as normal, or [as `@runtime` protocols, which means `issubclass` works](https://mypy.readthedocs.io/en/latest/protocols.html?highlight=runtime#using-isinstance-with-protocols) by doing a structural subtyping check.  This should be *mostly* compatible with the existing interface declarations:

- you can still subclass them to get concrete implementations
- `isinstance` will still work, if they're decorated with `@runtime`
- `typing_extensions` does support python 2
- you can have a class decorator that insists on compliance with an interface (I described this a while ago, here: https://github.com/python/mypy/issues/4717#issuecomment-454609539)

The one problem is that I don't know of any way to give a `Protocol` a literal concrete `.register` classmethod without it thereby insisting that every adherent thereto *also* have a `.register` classmethod.

To maintain compatibility, you *could* define the classmethod in an `if not TYPE_CHECKING` block, which would define it *only* at runtime; it would not type-check for external libraries to call `.register`, but if they were using `register_interface` that could be appropriately modified to make it do what it needs to do.  And you could get rid of `verify_interface` and just let Protocol's existing subclasshook do the job.

**Comment by alex** [comment] 2019-07-29 03:59
I don't think we care about 3rd parties registering implementations of our ABCs, so changing how that works seems fine.

**Comment by glyph** [comment] 2019-08-05 04:51
Okay, in that case I guess we're almost to the point where I could try my hand at a PR...

**Comment by jlaine** [comment] 2019-10-18 15:23
FYI I have submitted a PR against typeshed to expand the `cryptography` typings: https://github.com/python/typeshed/pull/3307

**Comment by jlaine** [comment] 2019-10-19 09:22
@reaperhulk and @alex the typings I submitted to typeshed are almost complete. Only the x509 module needs a little more love to fully support all extension types. Could you possibly weigh in on whether the PR against typeshed is going the way you want?

**Comment by jlaine** [comment] 2019-11-29 22:51
mypy 0.750 just shipped, and it includes the type stubs I submitted to `typeshed`, any improvements are welcome.

**Comment by toppk** [comment] 2019-12-02 21:48
@jlaine where do you want bug reports?  

It seems that CertificateSigningRequest.public_bytes() takes an "encoding parameter"

https://cryptography.io/en/latest/x509/reference/#cryptography.x509.CertificateSigningRequest.public_bytes

https://github.com/python/typeshed/blob/master/third_party/2and3/cryptography/x509.pyi#L208

**Comment by reaperhulk** [comment] 2020-07-19 02:14
Since these are going into typeshed already I'm going to close this for now. Once we drop 2.7 support we'll be more capable of directly supporting this in a way that isn't insanely frustrating.

**Closed by reaperhulk** 2020-07-19 02:14 UTC
Labels: blocked-on-upstream
