### ISSUE TITLE
"path_length must be None when ca is False" error while ca is True

### ISSUE THREAD

**Issue by zout** [pyca/cryptography#4370] opened 2018-07-25 09:18 UTC
It somehow does not see that the CA value is True, throwing the this message:
```plain
$ python3 cert_check_issue.py
Traceback (most recent call last):
  File "cert_check_issue.py", line 15, in <module>
    basic_constrains = cert.extensions.get_extension_for_oid(ExtensionOID.BASIC_CONSTRAINTS)
  File "/usr/local/lib/python3.5/dist-packages/cryptography/utils.py", line 161, in inner
    result = func(instance)
  File "/usr/local/lib/python3.5/dist-packages/cryptography/hazmat/backends/openssl/x509.py", line 134, in extensions
    self._backend, self._x509
  File "/usr/local/lib/python3.5/dist-packages/cryptography/hazmat/backends/openssl/decode_asn1.py", line 238, in parse
    value = handler(backend, ext_data)
  File "/usr/local/lib/python3.5/dist-packages/cryptography/hazmat/backends/openssl/decode_asn1.py", line 328, in _decode_basic_constraints
    return x509.BasicConstraints(ca, path_length)
  File "/usr/local/lib/python3.5/dist-packages/cryptography/x509/extensions.py", line 345, in __init__
    raise ValueError("path_length must be None when ca is False")
ValueError: path_length must be None when ca is False
```

The script I've used:
```python
from cryptography import x509
from cryptography.hazmat.backends import default_backend
from cryptography.x509.oid import ExtensionOID


# Read cert
cert_data = b'''
-----BEGIN CERTIFICATE-----
MIIGNDCCBBygAwIBAgIDGGoyMA0GCSqGSIb3DQEBCwUAMIGQMQswCQYDVQQGEwJV
QTEZMBcGA1UEBRMQVUEtMTYyODY0NDEtMDAwMTE8MDoGA1UECgwzUG9seWdyYXBo
IGNvbWJpbmUgVUtSQUlOQSBmb3Igc2VjdXJpdGllcyBwcm9kdWN0aW9uMREwDwYD
VQQLDAhTQ1BEIFBDVTEVMBMGA1UEAwwMQ1NDQS1VS1JBSU5FMB4XDTE1MDMyNDEy
NTc0MFoXDTMwMDYyNDEyNTc0MFowgZAxCzAJBgNVBAYTAlVBMRkwFwYDVQQFExBV
QS0xNjI4NjQ0MS0wMDAxMTwwOgYDVQQKDDNQb2x5Z3JhcGggY29tYmluZSBVS1JB
SU5BIGZvciBzZWN1cml0aWVzIHByb2R1Y3Rpb24xETAPBgNVBAsMCFNDUEQgUENV
MRUwEwYDVQQDDAxDU0NBLVVLUkFJTkUwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAw
ggIKAoICAQDH8j4RT9nXeVh2LGBxJynUasebCZlEztPnKAV5KAF+lcPDB1pl0QdQ
+x0vHkCgPncOblpx7kmgMKZexPzEf1JdDj5jl2l0AvPwI6jjeQNZ9er/UirmnXWT
3F5pP8CRC4C4txS6ee5zeB3eKWB1P8+m3nDKUHvBipPWYDXAmMREvjbrRlqJAjoY
tNlDHm83sevTJl/Yym7Cu2TkH2aLUf7WqToLmJT6gMV3xUJr1EaVsUcILC4AOmVQ
S2YiBt8N6QtFcbDd7dZHHON337VY8DZ5M7VCIDrReRosgNftyhjKHHFa4oGAyjzY
KdPCEs5sqnQ3lgA9dpifPn/S8FTm5pcY6OokeQ7qepGiuc4uUlmhXj76iG5VglcI
4iodCp55dcicyHpGSHFAU0AMoNVlFPIK+VoqOqmGIJs6fDPx+pdjl/rrPKqe2jML
jGjUgOqQFJpiHUpsi+K9zyVP+xzH0NKhi+E/Vz6B6MuzHC86bx3NKWhV4shxL62F
pNxVRpndP3I2WRxJRCTXbqDoqxg45hRluQ2tZou41Mq8G8g8xGLt4e/bRcuWM0LF
TiftaexlawkoLYJ4nAvyowfr6VvO984SrwRzLn37cijQnm7NcB2/Avge1LuMRvV+
VtUa92xLlx/20xQE8omocCXzre54RcocuNik/02ID4lPdiT3xBPlowIDAQABo4GU
MIGRMB0GA1UdDgQWBBRgNP/WOOYC4wrv2JxxON7M0G0g9DAfBgNVHSMEGDAWgBRg
NP/WOOYC4wrv2JxxON7M0G0g9DAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgw
BgEBAQIBADArBgNVHRAEJDAigA8yMDE1MDMyNDEyNTc0MFqBDzIwMjAwMzI0MTI1
NzQwWjANBgkqhkiG9w0BAQsFAAOCAgEADtyi2cVGhmO5fNcxdy/gjYfOZCT6/b9v
hjXk36Ln6d13TLObi1Pc9icu0xfDj2EsqO9kEFrsOvnBsgG3mCXl/AYQqz8ueJw4
0L2Yorc+KBcBXbziLgFiAB9EwzF4cMAGoxLPu8gArVSwZVD9IT911EUB02yu/7pG
EMBgvFz2qPBExuXYc0PxYBn7blS3KbNdjvZm4+g0DAu4y9e7jGyweIpGBUMpx16f
EqCzrBpWj1dY40UycaK78GbCDZgv/5GkHFu+2d5e9UJaTtmAFTcpLwvuxO+Nsr60
paTefrWRmpf9WXNoiAIxxBPfjMEcqTqom116xpO0E4900q28QeVAdwy/sZ9FJOAz
Srv3npBs8sk+M97qS9tkUfbhyc7c+5ZTCFm1fAXqmpcNzyO8EpfURhS2CCvga/5s
QXrgdfaB7lvtjfDoUrmnkGgpRJACXoRNPerxHQu2qHEhf8fKekBCSQrK0Bayacbp
kwVdIETOKAoIn1YSQJbWcSGHwAY/g3s1tH9aXvCnbNcD/ikzAxUiJygbmDngda2U
/akdHhbh8z/YUWdUdMRhU2YLBphsVfk5kqlSvoQi6mW+u7C3vQuxHr/2VXYkeXf1
jtuJaV5m9XiBX2N89ks8puNO7BlRO9wIeTcsdFljc1iwQMcDIO4YdtfdwEaJP1gR
w6aCFLjz4hQ=
-----END CERTIFICATE-----
'''
cert = x509.load_pem_x509_certificate(cert_data, default_backend())

basic_constrains = cert.extensions.get_extension_for_oid(ExtensionOID.BASIC_CONSTRAINTS)
is_ca = basic_constrains.value.ca

# it won't make it till here
print('is CA:', is_ca)
```

When I read it into `openssl` using the following command: `openssl x509 -in CSCA-UKRAINE_1600050.pem  -text -noout` it says that CA is TRUE. See output:

```plain
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 1600050 (0x186a32)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=UA/serialNumber=UA-16286441-0001, O=Polygraph combine UKRAINA for securities production, OU=SCPD PCU, CN=CSCA-UKRAINE
        Validity
            Not Before: Mar 24 12:57:40 2015 GMT
            Not After : Jun 24 12:57:40 2030 GMT
        Subject: C=UA/serialNumber=UA-16286441-0001, O=Polygraph combine UKRAINA for securities production, OU=SCPD PCU, CN=CSCA-UKRAINE
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (4096 bit)
                Modulus:
                    00:c7:f2:3e:11:4f:d9:d7:79:58:76:2c:60:71:27:
                    29:d4:6a:c7:9b:09:99:44:ce:d3:e7:28:05:79:28:
                    01:7e:95:c3:c3:07:5a:65:d1:07:50:fb:1d:2f:1e:
                    40:a0:3e:77:0e:6e:5a:71:ee:49:a0:30:a6:5e:c4:
                    fc:c4:7f:52:5d:0e:3e:63:97:69:74:02:f3:f0:23:
                    a8:e3:79:03:59:f5:ea:ff:52:2a:e6:9d:75:93:dc:
                    5e:69:3f:c0:91:0b:80:b8:b7:14:ba:79:ee:73:78:
                    1d:de:29:60:75:3f:cf:a6:de:70:ca:50:7b:c1:8a:
                    93:d6:60:35:c0:98:c4:44:be:36:eb:46:5a:89:02:
                    3a:18:b4:d9:43:1e:6f:37:b1:eb:d3:26:5f:d8:ca:
                    6e:c2:bb:64:e4:1f:66:8b:51:fe:d6:a9:3a:0b:98:
                    94:fa:80:c5:77:c5:42:6b:d4:46:95:b1:47:08:2c:
                    2e:00:3a:65:50:4b:66:22:06:df:0d:e9:0b:45:71:
                    b0:dd:ed:d6:47:1c:e3:77:df:b5:58:f0:36:79:33:
                    b5:42:20:3a:d1:79:1a:2c:80:d7:ed:ca:18:ca:1c:
                    71:5a:e2:81:80:ca:3c:d8:29:d3:c2:12:ce:6c:aa:
                    74:37:96:00:3d:76:98:9f:3e:7f:d2:f0:54:e6:e6:
                    97:18:e8:ea:24:79:0e:ea:7a:91:a2:b9:ce:2e:52:
                    59:a1:5e:3e:fa:88:6e:55:82:57:08:e2:2a:1d:0a:
                    9e:79:75:c8:9c:c8:7a:46:48:71:40:53:40:0c:a0:
                    d5:65:14:f2:0a:f9:5a:2a:3a:a9:86:20:9b:3a:7c:
                    33:f1:fa:97:63:97:fa:eb:3c:aa:9e:da:33:0b:8c:
                    68:d4:80:ea:90:14:9a:62:1d:4a:6c:8b:e2:bd:cf:
                    25:4f:fb:1c:c7:d0:d2:a1:8b:e1:3f:57:3e:81:e8:
                    cb:b3:1c:2f:3a:6f:1d:cd:29:68:55:e2:c8:71:2f:
                    ad:85:a4:dc:55:46:99:dd:3f:72:36:59:1c:49:44:
                    24:d7:6e:a0:e8:ab:18:38:e6:14:65:b9:0d:ad:66:
                    8b:b8:d4:ca:bc:1b:c8:3c:c4:62:ed:e1:ef:db:45:
                    cb:96:33:42:c5:4e:27:ed:69:ec:65:6b:09:28:2d:
                    82:78:9c:0b:f2:a3:07:eb:e9:5b:ce:f7:ce:12:af:
                    04:73:2e:7d:fb:72:28:d0:9e:6e:cd:70:1d:bf:02:
                    f8:1e:d4:bb:8c:46:f5:7e:56:d5:1a:f7:6c:4b:97:
                    1f:f6:d3:14:04:f2:89:a8:70:25:f3:ad:ee:78:45:
                    ca:1c:b8:d8:a4:ff:4d:88:0f:89:4f:76:24:f7:c4:
                    13:e5:a3
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Subject Key Identifier:
                60:34:FF:D6:38:E6:02:E3:0A:EF:D8:9C:71:38:DE:CC:D0:6D:20:F4
            X509v3 Authority Key Identifier:
                keyid:60:34:FF:D6:38:E6:02:E3:0A:EF:D8:9C:71:38:DE:CC:D0:6D:20:F4

            X509v3 Key Usage: critical
                Certificate Sign, CRL Sign
            X509v3 Basic Constraints: critical
                CA:TRUE, pathlen:0
            X509v3 Private Key Usage Period:
                Not Before: Mar 24 12:57:40 2015 GMT, Not After: Mar 24 12:57:40 2020 GMT
    Signature Algorithm: sha256WithRSAEncryption
         0e:dc:a2:d9:c5:46:86:63:b9:7c:d7:31:77:2f:e0:8d:87:ce:
         64:24:fa:fd:bf:6f:86:35:e4:df:a2:e7:e9:dd:77:4c:b3:9b:
         8b:53:dc:f6:27:2e:d3:17:c3:8f:61:2c:a8:ef:64:10:5a:ec:
         3a:f9:c1:b2:01:b7:98:25:e5:fc:06:10:ab:3f:2e:78:9c:38:
         d0:bd:98:a2:b7:3e:28:17:01:5d:bc:e2:2e:01:62:00:1f:44:
         c3:31:78:70:c0:06:a3:12:cf:bb:c8:00:ad:54:b0:65:50:fd:
         21:3f:75:d4:45:01:d3:6c:ae:ff:ba:46:10:c0:60:bc:5c:f6:
         a8:f0:44:c6:e5:d8:73:43:f1:60:19:fb:6e:54:b7:29:b3:5d:
         8e:f6:66:e3:e8:34:0c:0b:b8:cb:d7:bb:8c:6c:b0:78:8a:46:
         05:43:29:c7:5e:9f:12:a0:b3:ac:1a:56:8f:57:58:e3:45:32:
         71:a2:bb:f0:66:c2:0d:98:2f:ff:91:a4:1c:5b:be:d9:de:5e:
         f5:42:5a:4e:d9:80:15:37:29:2f:0b:ee:c4:ef:8d:b2:be:b4:
         a5:a4:de:7e:b5:91:9a:97:fd:59:73:68:88:02:31:c4:13:df:
         8c:c1:1c:a9:3a:a8:9b:5d:7a:c6:93:b4:13:8f:74:d2:ad:bc:
         41:e5:40:77:0c:bf:b1:9f:45:24:e0:33:4a:bb:f7:9e:90:6c:
         f2:c9:3e:33:de:ea:4b:db:64:51:f6:e1:c9:ce:dc:fb:96:53:
         08:59:b5:7c:05:ea:9a:97:0d:cf:23:bc:12:97:d4:46:14:b6:
         08:2b:e0:6b:fe:6c:41:7a:e0:75:f6:81:ee:5b:ed:8d:f0:e8:
         52:b9:a7:90:68:29:44:90:02:5e:84:4d:3d:ea:f1:1d:0b:b6:
         a8:71:21:7f:c7:ca:7a:40:42:49:0a:ca:d0:16:b2:69:c6:e9:
         93:05:5d:20:44:ce:28:0a:08:9f:56:12:40:96:d6:71:21:87:
         c0:06:3f:83:7b:35:b4:7f:5a:5e:f0:a7:6c:d7:03:fe:29:33:
         03:15:22:27:28:1b:98:39:e0:75:ad:94:fd:a9:1d:1e:16:e1:
         f3:3f:d8:51:67:54:74:c4:61:53:66:0b:06:98:6c:55:f9:39:
         92:a9:52:be:84:22:ea:65:be:bb:b0:b7:bd:0b:b1:1e:bf:f6:
         55:76:24:79:77:f5:8e:db:89:69:5e:66:f5:78:81:5f:63:7c:
         f6:4b:3c:a6:e3:4e:ec:19:51:3b:dc:08:79:37:2c:74:59:63:
         73:58:b0:40:c7:03:20:ee:18:76:d7:dd:c0:46:89:3f:58:11:
         c3:a6:82:14:b8:f3:e2:14
```

Because of this you are also not able to read the "Subject Key Identifier", and that's what I need. This is by the way a official certificate from a country, so I can't change that.

Extra info: I also have a Italian country certificate that has the same issue. But there CA is `False` but the `path_length` is set. OpenSSL does not have any issues with that. See output: (Yes I know about 
https://github.com/pyca/cryptography/issues/3856, but I'd like to be able to ignore it because these certs do excist, and I would like to be able to read them).
```plain
$ openssl x509 -in Italian\ Country\ Signer\ CA_801.pem  -text -noout
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 801 (0x321)
    Signature Algorithm: sha1WithRSAEncryption
        Issuer: C=IT, O=MINISTERO DELL'INTERNO, OU=PE, CN=CERTIFICATION AUTHORITY 01
        Validity
            Not Before: May 19 11:02:20 2016 GMT
            Not After : Aug 20 11:02:20 2026 GMT
        Subject: C=IT, O=Ministry of Interior, OU=National Electronic Center of State Police, CN=Italian Country Signer CA
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (4096 bit)
                Modulus:
                    00:d4:b7:b2:9a:d7:c9:95:e4:a3:43:06:10:c5:83:
                    cb:79:b2:ad:42:ba:be:e9:2a:18:bd:bd:27:79:69:
                    b8:de:00:f3:98:03:d0:83:11:6f:78:5a:c9:fe:4f:
                    30:e5:b2:ac:64:a6:7e:39:70:4b:15:c3:55:a0:77:
                    86:6e:1d:2b:66:41:30:6a:83:dc:7e:31:3c:31:ab:
                    f7:84:83:95:88:bd:ae:ac:dd:a6:90:32:4f:83:f1:
                    c1:13:ab:b7:cb:72:90:63:23:25:02:99:c6:e5:00:
                    52:49:64:6b:48:44:fa:d1:e5:7a:29:26:ea:35:c5:
                    89:9e:86:f7:8a:b3:42:e4:9d:94:b0:e2:5e:a3:b9:
                    69:dc:76:90:92:c5:f4:22:07:0d:a6:4b:23:20:4a:
                    e8:d7:ca:cc:d0:05:40:1a:4e:58:79:fb:a9:a9:40:
                    2c:b2:d7:97:cf:4e:80:4d:ee:bd:5a:1a:ea:ce:b0:
                    4b:18:d4:8d:7a:1e:86:9d:92:47:4f:f7:28:29:de:
                    52:03:6e:10:30:7d:e9:92:d2:79:31:bd:80:86:ef:
                    ea:7d:3a:b7:03:8d:b3:46:85:d5:e3:35:b6:47:a4:
                    3f:d5:b6:0e:42:98:34:f1:67:a7:81:9f:5d:70:6d:
                    90:91:5a:cf:27:2f:ea:bd:44:29:9d:6f:ad:ce:a6:
                    b3:a8:3a:55:7b:ce:db:fc:b7:36:90:70:0c:df:7a:
                    cb:fb:10:03:61:9c:ec:7b:84:9a:55:c1:6b:ab:02:
                    0c:9c:3c:04:cd:31:fb:fe:71:dd:8d:a6:48:22:7e:
                    41:22:31:e4:d3:59:ee:40:a3:db:e4:94:e1:b8:75:
                    b0:17:17:09:9f:3b:4d:7a:b7:b8:12:b0:7a:a4:75:
                    d7:cc:d5:3a:d7:9a:44:ee:5b:92:e7:75:cd:3a:20:
                    51:44:61:87:08:f9:e7:cf:11:b3:18:13:ad:de:28:
                    9e:d4:cb:c9:13:cc:72:c1:49:31:ee:92:e8:b0:a5:
                    17:77:5e:bc:3e:19:15:0d:0a:ee:d2:b9:00:9b:54:
                    0d:22:cc:c3:38:67:45:22:df:6c:0a:48:f6:aa:25:
                    b9:47:5a:59:f1:da:2a:aa:b0:fd:93:d5:f3:dc:98:
                    6a:91:a9:5b:51:47:ee:46:ea:d5:a1:17:5e:7e:90:
                    b5:89:24:89:f8:a0:fd:de:f2:e3:ff:e1:70:46:f4:
                    52:15:f5:e1:92:cd:c5:5f:44:f5:c7:62:b9:4f:20:
                    95:8c:9e:3f:b9:b1:20:59:03:4a:87:54:07:35:9c:
                    d9:20:18:8f:b9:17:8d:99:25:a4:b5:01:d2:92:4f:
                    54:7e:e4:38:5f:b5:64:2a:0e:c4:25:47:c1:8e:97:
                    c5:5c:69
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints: critical
                CA:FALSE, pathlen:0
            X509v3 Subject Key Identifier:
                85:2D:F7:A7:0A:51:2D:83:10:3D:FB:C9:F6:28:CB:6B:1C:EE:55:91
            X509v3 Authority Key Identifier:
                keyid:B0:BF:3B:B9:EC:EB:C7:20:97:4C:1D:13:A5:90:5A:1A:61:35:89:A0

            X509v3 Subject Alternative Name:
                email:spoc-ita@interno.it, URI:http://csca-ita.interno.gov.it
            X509v3 CRL Distribution Points:

                Full Name:
                  URI:http://csca-ita.interno.gov.it/certificatiCSCA/CRL_CSCA.crl

            X509v3 Key Usage: critical
                Certificate Sign, CRL Sign
    Signature Algorithm: sha1WithRSAEncryption
         70:2d:7c:9c:50:8a:36:2e:26:6a:1b:52:ee:b8:7f:1b:5f:e9:
         e5:b2:23:27:ef:6e:5f:d7:93:7b:b3:6b:49:fd:ca:53:94:ac:
         09:b0:79:66:8f:19:5c:7b:68:7c:38:1f:06:83:e3:a9:07:ce:
         c2:95:43:2e:b7:7e:ce:0d:ce:ab:15:b4:f8:31:db:4f:8f:c7:
         32:20:70:42:97:1c:c6:42:f0:32:3d:18:da:67:78:a7:ee:f7:
         29:4e:56:75:eb:14:82:f8:5f:2a:74:11:72:7c:d9:e4:3c:06:
         13:df:25:a9:6e:69:ba:10:10:4c:4e:56:be:38:a8:a8:44:aa:
         6c:7e:53:b7:48:a0:87:29:83:5e:74:dd:cb:8a:27:01:81:ee:
         1c:dc:48:a4:bb:df:31:5c:32:53:b0:c6:5e:65:c9:11:4b:ee:
         97:e2:7a:e0:64:ae:a2:8e:c7:8f:25:3b:46:2a:14:a6:de:2b:
         18:aa:0d:c6:7a:7f:c9:e0:5a:81:f1:e7:a7:21:20:67:13:2f:
         50:5f:60:b5:ca:24:49:0f:87:55:d4:45:8b:22:f1:78:47:52:
         91:1b:4a:1b:5c:4c:63:33:11:6d:4c:fa:16:b0:d3:21:65:7c:
         f1:6b:e3:ac:e5:c1:ba:81:1c:a0:95:b5:32:e7:9b:6f:af:42:
         b0:0c:e4:20:cc:f6:df:19:1a:70:c6:8a:93:23:c5:b7:ef:04:
         aa:cd:e1:6b:93:8c:2c:07:dd:40:89:56:48:5f:85:c7:0a:e3:
         6c:47:33:01:4c:99:60:12:ae:0d:9b:ce:bc:4f:da:12:21:1b:
         d2:f8:a7:22:ac:52:0d:0b:91:f3:47:fc:67:73:9c:7d:39:b4:
         f1:91:f1:dc:04:9b:21:82:ce:0d:ce:58:83:74:2a:86:0a:cf:
         6f:99:7d:38:8f:33:bb:bd:8f:1b:bc:3e:8c:a8:87:23:1f:33:
         49:57:bf:fb:00:57:0f:98:ca:75:c9:40:78:4d:ac:de:63:48:
         9f:06:b2:13:55:86:20:b9:71:1c:15:27:7d:84:52:9f:a7:a2:
         00:52:01:71:d5:ec:de:2f:e7:48:d6:fc:6c:51:32:20:cf:4a:
         f9:61:4a:df:64:19:9a:31:16:32:fa:a2:e6:48:85:29:9d:76:
         81:3b:96:b5:16:93:1b:10:79:0a:c9:0e:98:50:f2:32:46:97:
         f6:5d:e3:11:8b:a0:ba:3b:b6:f4:1b:b4:54:03:7a:ad:8c:2b:
         3d:e1:19:0e:92:b1:7a:a7:52:0b:d8:17:92:b7:a8:2c:ab:87:
         dd:30:d4:1e:42:fd:8d:09:78:02:f5:f1:aa:5c:6f:56:a8:52:
         2d:81:51:61:89:72:7b:17
``` 

Versions:
 - Python: 3.5.2
 - cryptography==2.2.2
 - cryptography==2.3 (but also checked with 2.2.2)
 - cffi==1.11.5
 - pip: 10.0.1
 - setuptools: 20.7.0

I installed via PIP.

**Comment by zout** [comment] 2018-07-25 09:50
I wrote a monkey patch for it now:
```python
# Monkey patch the cryptography lib
import six
from cryptography.x509 import BasicConstraints


def monkeypatched_crypto_init(self, ca, path_length):
    if not isinstance(ca, bool):
        raise TypeError("ca must be a boolean value")

    if path_length is not None and not ca:
        print("Old Value Error: path_length must be None when ca is False")
        #raise ValueError("path_length must be None when ca is False")

    if (
            path_length is not None and
            (not isinstance(path_length, six.integer_types) or path_length < 0)
    ):
        raise TypeError(
            "path_length must be a non-negative integer or None"
        )

    self._ca = ca
    self._path_length = path_length


BasicConstraints.__init__ = monkeypatched_crypto_init
# End monkey patch
```

**Comment by reaperhulk** [comment] 2018-07-25 10:39
Thanks for the report! The issue here is that the basic constraints extension is ASN1 encoded as follows:

```
    0:d=0  hl=2 l=   6 cons: SEQUENCE
    2:d=1  hl=2 l=   1 prim: BOOLEAN           :1
    5:d=1  hl=2 l=   1 prim: INTEGER           :00
```

Our parser currently requires that all bits be set to 1 (aka integer 255) for boolean TRUE. This is the rule for DER encoded data. BER is more lax and allows any non-zero value. X509 has historically been an unfortunate mix of "mostly DER but sometimes some BER ideas slip in there".

Strictly speaking this certificate is encoded improperly, but it would be worthwhile to see what other implementations do before we decide what path to take. Judging by OpenSSL's tolerance it may be that this (while wrong) is the sort of thing we need to handle.

**Comment by reaperhulk** [comment] 2018-07-25 11:47
The value is arguably **not** true. It is the bit value `00000001` inside an ASN.1 boolean, which BER encoding says corresponds to true, but DER says is false (because only `11111111` is true). Our current code treats this as false because we adhere to DER. In practice we may need to treat this as true if most other parsers treat it as such, but it sounds like macOS at least is attempting to use strict DER parsing like we are.

There is a separate issue that it is sometimes desirable to parse broken certificates even if they are broken (discussion: #3856 and an old PR: #3862). That's still an outstanding issue that needs to be revisited.

**Comment by zout** [comment] 2018-07-25 11:55
Okay, I understand. How can I help to address this. 
The monkey patch is not a great way to ignore a error that does not bother me. I need to read the "Subject Key Identifier" and the validation of the CA value blocks me from doing that.
I see it like this: You should let the developer decide when something is a problem and introduce a "strict" mode (default on o.c.) to fail it on some issues.

**Comment by reaperhulk** [comment] 2018-07-25 13:46
We've discussed some potential avenues forward and the consensus is that we need to build a hazmat layer x509 parser that allows (some) broken things and then implement the current x509 layer on top of that. However, that's a large task and as a volunteer project we don't have a timeline for that at the moment. Tentatively it will be in the next milestone. If you'd like to potentially contribute that'd be great, but be aware that it will involve overhauling almost all the existing x509 layer (including the backend where we use our C bindings).

**Comment by alex** [comment] 2018-08-29 22:29
Closing as a dupe of #3856

**Closed by alex** 2018-08-29 22:29 UTC
