### ISSUE TITLE
In FIPS mode, cryptography throws error in ssh connect

### ISSUE THREAD

**Issue by kparamas** [pyca/cryptography#4740] opened 2019-01-28 03:39 UTC
If you're filing a bug (as opposed to a feature request), please try the
following things:

Related issue #4682 

Version of RPMS used:

python-bcrypt-3.1.4-1.x86_64
python-pynacl-1.2.1-1.x86_64
cryptography-2.0.3-4.el7.centos.x86_64
cffi-1.7.0-4.el7.centos.x86_64
setuptools-20.2.2-4.el7.centos.x86_64
paramiko-scp-1.10.2-4.el7.centos.x86_64
paramiko-2.4.2-4.el7.centos.x86_64

sh-4.2# rpm -qa | grep openssl
openssl-perl-1.0.2k-3.el7.centos.x86_64
openssl-libs-1.0.2k-3.el7.centos.x86_64
openssl-1.0.2k-3.el7.centos.x86_64
xmlsec1-openssl-1.2.20-5.el7.x86_64

Execute the program with proper credentials:

```
import paramiko
import sys

## EDIT SSH DETAILS ##

SSH_ADDRESS = "10.2.x.x"
SSH_USERNAME = "xxxx"
SSH_PASSWORD = "xxxx"
SSH_COMMAND = "echo 'Hello World!'"

## CODE BELOW ##

ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())

ssh_stdin = ssh_stdout = ssh_stderr = None

try:
    ssh.connect(SSH_ADDRESS, username=SSH_USERNAME, password=SSH_PASSWORD)
    ssh_stdin, ssh_stdout, ssh_stderr = ssh.exec_command(SSH_COMMAND)
except Exception as e:
    sys.stderr.write("SSH connection error: {0}".format(e))

if ssh_stdout:
    sys.stdout.write(ssh_stdout.read())
if ssh_stderr:
    sys.stderr.write(ssh_stderr.read())
```

Error message:

sh-4.2# python python_ssh.py 
No handlers could be found for logger "paramiko.transport"
SSH connection error: Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLErrorWithText(code=755437694L, lib=45, func=113, reason=126, reason_text='error:2D07107E:FIPS routines:FIPS_drbg_generate:not instantiated')])

**Comment by reaperhulk** [comment] 2019-02-02 00:46
This is well outside our supported configurations (we do not officially support FIPS), but you could try calling `backend.activate_builtin_random()` (imported via `from cryptography.hazmat.backends.openssl.backend import backend`) and see if that resolves the issue.

**Comment by alex** [comment] 2019-02-13 19:58
No feedback after nearly two weeks. If there's more details/a confirmed bug here we'll reopen.

**Comment by km-repo** [comment] 2019-02-17 03:44
I faced the same problem in FIPS and  python-cryptography version 2.3.1. Commenting out the line `self._lib.RAND_cleanup()` in `activate_builtin_random` in the file `cryptography/hazmat/backends/openssl/backend.py` made it to work.
Is this a safe change ?

**Comment by reaperhulk** [comment] 2019-02-18 06:38
`RAND_cleanup` does nothing as of 1.1.0+, but here's what it does in older versions:

```
 void RAND_cleanup(void)
     {
     const RAND_METHOD *meth = RAND_get_rand_method();
     if (meth && meth->cleanup)
        meth->cleanup();
     RAND_set_rand_method(NULL);
     }
```

Failing to call that may result in the built-in engine not being activated again. I can debug this if someone wants to build a docker container that can replicate the bug for me, but otherwise it's going to be a bit difficult to figure this out without a user with significant OpenSSL expertise stepping forward.

**Comment by km-repo** [comment] 2019-07-25 19:50
I have uploaded a docker image to dockerhub.
kmrepo/fips-centos6:dev2221

There are test scripts in  /root/tests/. This is the output that we are seeing on both the scripts -
```
$ python test1.py 
Traceback (most recent call last):
  File "test1.py", line 3, in <module>
    print jwk.JWK(generate='RSA', size=2048).export()
  File "/opt/lib/python2.7/site-packages/jwcrypto/jwk.py", line 231, in __init__
    self.generate_key(**kwargs)
  File "/opt/lib/python2.7/site-packages/jwcrypto/jwk.py", line 255, in generate_key
    gen(params)
  File "/opt/lib/python2.7/site-packages/jwcrypto/jwk.py", line 286, in _generate_RSA
    key = rsa.generate_private_key(pubexp, size, default_backend())
  File "/opt/lib/python2.7/site-packages/cryptography/hazmat/primitives/asymmetric/rsa.py", line 119, in generate_private_key
    return backend.generate_rsa_private_key(public_exponent, key_size)
  File "/opt/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 361, in generate_rsa_private_key
    self.openssl_assert(res == 1)
  File "/opt/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 105, in openssl_assert
    return binding._openssl_assert(self._lib, ok)
  File "/opt/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 76, in _openssl_assert
    errors_with_text
cryptography.exceptions.InternalError: Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLErrorWithText(code=755437694L, lib=45, func=113, reason=126, reason_text='error:2D07107E:FIPS routines:FIPS_drbg_generate:not instantiated')])
```
```
$ python test2.py <sftpserver> <username> <password>
No handlers could be found for logger "paramiko.transport"
Traceback (most recent call last):
  File "test2.py", line 14, in <module>
    ssh_client.connect(server, 22, username, password)
  File "/opt/lib/python2.7/site-packages/paramiko/client.py", line 397, in connect
    t.start_client(timeout=timeout)
  File "/opt/lib/python2.7/site-packages/paramiko/transport.py", line 587, in start_client
    raise e
cryptography.exceptions.InternalError: Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLErrorWithText(code=755437694L, lib=45, func=113, reason=126, reason_text='error:2D07107E:FIPS routines:FIPS_drbg_generate:not instantiated')])
Exception in thread Thread-2 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/opt/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/opt/lib/python2.7/threading.py", line 1083, in run
  File "/opt/lib/python2.7/threading.py", line 586, in set
  File "/opt/lib/python2.7/threading.py", line 407, in notifyAll
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
```

**Comment by reaperhulk** [comment] 2019-07-25 19:54
Thanks @km-repo I see the same errors now.

**Comment by reaperhulk** [comment] 2019-07-25 20:02
Where is `FIPS_mode_set` being called here? It's already activated when I run these scripts. Incidentally adding:

```
from cryptography.hazmat.backends.openssl.backend import backend
backend._lib.FIPS_mode_set(0)
backend._lib.FIPS_mode_set(1)
```

will fix the issue, but I'd like to understand the order of operations here. It seems like somehow FIPS mode is set by default when OpenSSL starts (or possibly read from a config somewhere?), but cryptography breaks initialization in some fashion. Toggling FIPS mode like above will cause it to properly instantiate the FIPS DRBG, but that's not an elegant workaround.

**Comment by tiran** [comment] 2019-07-25 20:04
This issue is missing one important point. If you actually care about FIPS validation, then you must use an approved SSH library. Paramiko depends on cryptographic libraries that are not FIPS approved, e.g. FIPS. Paramiko may use primitives in a way, that are not allowed.

You may be able to get Paramiko running under FIPS enforced OpenSSL. But you certainly will violate FIPS.

**Comment by tiran** [comment] 2019-07-25 20:06
Ah sorry, this issue is no longer about SSH but jwcrypto, which @simo5 and I maintain.

**Comment by simo5** [comment] 2019-07-25 20:27
@reaperhulk FWIW, when the system is set in FIPS mode (kernel is passed fips=1), openssl will auto initialize fips mode, ideally there is no need to actively do so in code, and this is transparent to users (except for the algorithms that are disabled in FIPS mode of course).

**Comment by km-repo** [comment] 2019-07-25 21:37
@reaperhulk In this case, fips mode set is hardcoded in the recompiled openssl library. There is a marker file ```/etc/opt/fips``` that controls this mode (touching/removing this file will enable/disable fips).

**Comment by reaperhulk** [comment] 2019-07-25 22:21
Hmm okay. So we're clobbering the FIPS DRBG instantiation when we activate our own random (because we call `RAND_cleanup`), but `activate_builtin_random` doesn't properly cause it to re-initialize. Looks like `RAND_init_fips` does this, but we don't want to be calling that since almost all our callees won't be using FIPS (or won't even have it available).

It may be safe to remove the call to `RAND_cleanup`. As documented in the OpenSSL [docs](https://www.openssl.org/docs/man1.0.2/man3/RAND_set_rand_method.html).

> As of version 0.9.7, RAND_METHOD implementations are grouped together with other algorithmic APIs (eg. RSA_METHOD, EVP_CIPHER, etc) in ENGINE modules. If a default ENGINE is specified for RAND functionality using an ENGINE API function, that will override any RAND defaults set using the RAND API (ie. RAND_set_rand_method()).

I've just run some experiments and there's actually another bug here. In OpenSSL 1.1.1 (and possibly 1.1.0, haven't checked) `activate_builtin_random` actually doesn't cause it to revert to the OpenSSL built-in even when `RAND_cleanup` is called. In 1.0.2 failing to call `RAND_cleanup` prevents reversion to the built-in random. Maybe we're doing this wrong and should be using another approach? (And perhaps that approach will work properly with FIPS)

**Comment by simo5** [comment] 2019-07-26 15:55
CCng @t8m to see if he has any advice in this case

**Comment by t8m** [comment] 2019-07-26 16:00
RAND_cleanup is no-op on 1.1. Why are you replacing the builtin RNG?

**Comment by t8m** [comment] 2019-07-26 16:13
All this manipulation of RNG engines in python cryptography should be simply not done - definitely not at all with 1.1.x and newer and with 1.0.x in FIPS mode either.

**Comment by reaperhulk** [comment] 2019-07-26 16:42
@t8m cryptography has historically replaced default rand with an engine that uses `[/dev/urandom, getrandom, getentropy]` to gain fork safety. In our opinion the OpenSSL CSPRNG in 1.0.x is a huge footgun. As of 1.1.1 the builtin DRBG can be (but is not by default) initialized in a fork safe manner, but since we support 1.0.1+ (and will be stuck supporting 1.0.2 for quite a bit longer) we believe there's value in the alternate engine.

We do not explicitly support FIPS at all, but we're investigating this on a best effort basis. We would definitely be interested in any insight into how you're supposed to correctly use an ENGINE to replace RAND. It seems like the APIs should allow you to set a new RAND, have OpenSSL use that, and also allow you to disable it and go back to using the built-in DRBG. The permutations we care about:

## 1.0.x non-FIPS
Calling `RAND_cleanup` causes OpenSSL to properly switch between the ENGINE and builtin random with no issues

## 1.0.x FIPS
`RAND_cleanup` wipes the FIPS DRBG state so disabling the ENGINE and going back to the FIPS DRBG doesn't work without re-initializing it by toggling FIPS mode off and back on.

## 1.1.x
`RAND_cleanup` is a no-op in 1.1.x so once you set an ENGINE it never stops using it.

You can see the code used to activate/deactivate the random engine here:
https://github.com/pyca/cryptography/blob/784676de3381f039f95f998505d45fb9d56bd300/src/cryptography/hazmat/backends/openssl/backend.py#L130-L171

Does there exist a single path that will work for doing this across 1.0.x, 1.1.x, and FIPS enabled builds? If not, what is the proper way to disable an engine in 1.1.x? Is there a correct way to re-enable the FIPS DRBG after deactivating an engine, or is the only answer to never activate it in the first place if FIPS is detected?

**Comment by simo5** [comment] 2019-07-26 18:23
@reaperhulk I do not have an answer, but I am pretty sure that disabling the FIPS RNG and swapping it around would void FIPS, so that shouldn't be done.

**Comment by t8m** [comment] 2019-08-05 13:48
I do not think there is a single path. Please just not do the RNG engine juggling with 1.0.X in FIPS mode and with 1.1.x at all.

**Comment by dsethi** [comment] 2020-04-21 20:16
Has this issue been solved? We are running into same issue where we have to use paramiko on a fips enabled kernel. In case not, are there alternate python ssh libraries for this?

**Comment by reaperhulk** [comment] 2020-04-21 21:51
This has not been resolved. We got close but ran out of steam here: https://github.com/pyca/cryptography/pull/5024

If someone wants to dust that off, figure out the issues, and get it landed it will resolve the issue (and prevent regression in the future).

**Comment by dsethi** [comment] 2020-04-22 07:48
Yeah -- would really appreciate if someone could help out on this -- if it is something quick -- I can help out as well  (although have zero familiarity with paramiko codebase)

**Comment by simo5** [comment] 2020-04-22 12:18
@dsethi paramiko is probably not good anyway, last I looked it doesn't use, for example, KDFs from OpenSSL (I know because I added those KDFs to OpenSSL recently and they are only in master).
At Red Hat we are using bindings to libssh: https://github.com/ansible/pylibssh
because libssh has been made FIPS compliant by moving all of its cryptography in OpenSSL (note that we have patches to backport the SSH KDF to OpenSSL 1.1.1)

HTH

**Comment by reaperhulk** [comment] 2020-07-20 16:28
We’ve merged some additional FIPS handling code into cryptography. This code is not designed to make cryptography work elegantly with fips (at least not yet), but it does allow the test suite to pass and consumers who are starting up in fips mode already (typically via system policy in rhel) should see things work provided the things you’re trying to do are allowed algorithms in FIPS.

FIPS is an immense pain so absent active quality outside contribution this is likely to be as far as we go for now.

**Closed by reaperhulk** 2020-07-20 16:28 UTC

**Comment by simo5** [comment] 2020-07-20 16:40
Thanks for the work @reaperhulk, I think this is great progress already, should there be anything else really needed I will make sure to contribute PRs (disussed ahead of time and that you will find acceptable). But the work done so far is sufficient and we are greateful.
