### ISSUE TITLE
[Feature request] Allow Choice Of Symmetric Cipher

### ISSUE THREAD

**Issue by bhoefer2015** [pyca/cryptography#5269] opened 2020-06-09 13:39 UTC
Python 3.8.3, cryptography 2.9.x

In class [cryptography.hazmat.primitives.asymmetric.rsa.RSAPrivateKeyWithSerialization](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/rsa/#cryptography.hazmat.primitives.asymmetric.rsa.RSAPrivateKeyWithSerialization), this function:

&nbsp;&nbsp;&nbsp;&nbsp;[private_bytes(encoding, format, encryption_algorithm)](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/rsa/#cryptography.hazmat.primitives.asymmetric.rsa.RSAPrivateKeyWithSerialization.private_bytes)

...allows either _BestAvailableEncryption_ or _NoEncryption_ for its encryption_algorithm parameter.&nbsp; This feature request is to allow the specification of other ciphers since the best one ["may change over time."](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization/#cryptography.hazmat.primitives.serialization.BestAvailableEncryption)&nbsp; Allowing one to choose a cipher will prevent undesired surprises to users if/when that encrypt cipher changes.

**Comment by reaperhulk** [comment] 2020-06-09 21:40
This is a dupe of https://github.com/pyca/cryptography/issues/4272

We're willing to expose more control here but someone has to do the hard work of designing the API and implementing.

**Closed by reaperhulk** 2020-06-09 21:40 UTC
