### ISSUE TITLE
f = Fernet(key) produces a Segmentation Fault on Debian stretch

### ISSUE THREAD

**Issue by privatwolke** [pyca/cryptography#2592] opened 2015-12-27 17:00 UTC
I am running into a segfault when trying to create a new `Fernet` instance as demonstrated in the first example of the documentation:

Steps to reproduce
------------------------

```shell
$ pyvenv .ve
$ source .ve/bin/activate
(.ve) $ pip3 install cryptography
```

```python
>>> from cryptography.fernet import Fernet
>>> key = Fernet.generate_key()
>>> f = Fernet(key)
Segmentation fault
```

With `gdb` and debugging symbols:
```
Program received signal SIGSEGV, Segmentation fault.
0x00000000005bb4aa in PyObject_Call () at ../Objects/abstract.c:2054
2054	../Objects/abstract.c: No such file or directory.
```
[(see full backtrace here)](https://github.com/pyca/cryptography/files/72739/cryptography-segfault-backtrace.txt)

Version information
------------------------
* cryptography 1.1.2
* idna 2.0
* pyasn1 0.1.9
* six 1.10.0
* cffi 1.4.2

```
$ openssl version
OpenSSL 1.0.2e 3 Dec 2015
$ python --version
Python 3.4.4rc1
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux testing (stretch)
Release:	testing
Codename:	stretch
$ uname -a
Linux hostname 4.2.0-1-amd64 #1 SMP Debian 4.2.6-3 (2015-12-06) x86_64 GNU/Linux
```

Please let me know if I can provide any other debug information!

**Comment by alex** [comment] 2015-12-27 17:05
There's an extremely high chance this is caused by a GCC bug:
- https://bitbucket.org/cffi/cffi/issues/240/
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69037

**Comment by privatwolke** [comment] 2015-12-27 17:18
Confirmed. I switched gcc versions from 5.3.1 to 4.9.3 and the segfault is gone.

```shell
$ gcc-5 --version # produces segfaulting distribution
gcc-5 (Debian 5.3.1-4) 5.3.1 20151219

$ gcc-4.9 --version # produces working distribution
gcc-4.9 (Debian 4.9.3-10) 4.9.3
```

**Comment by alex** [comment] 2015-12-27 17:19
Ok, I'm going to close this issue since it's really an upstream bug. I've pinged some debian folks about seeing what's involved in getting the fix included.

**Closed by alex** 2015-12-27 17:19 UTC

**Comment by privatwolke** [comment] 2015-12-27 17:21
Awesome. Thank you!
