### ISSUE TITLE
i found this error when i installed mitmproxy on mac

### ISSUE THREAD

**Issue by Tom4t0** [pyca/cryptography#2480] opened 2015-11-18 02:27 UTC
➜  ~  mitmproxy
Traceback (most recent call last):
  File "/usr/local/bin/mitmproxy", line 9, in <module>
    load_entry_point('mitmproxy==0.14.0', 'console_scripts', 'mitmproxy')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 357, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2394, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2108, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Library/Python/2.7/site-packages/libmproxy/main.py", line 6, in <module>
    from netlib.version_check import check_pyopenssl_version, check_mitmproxy_version
  File "/Library/Python/2.7/site-packages/netlib/version_check.py", line 12, in <module>
    import OpenSSL
  File "/Library/Python/2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/Library/Python/2.7/site-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/Library/Python/2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 182, in <module>
    Binding.init_static_locks()
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 139, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 134, in _ensure_ffi_initialized
    cls._register_osrandom_engine()
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 99, in _register_osrandom_engine
    _openssl_assert(cls.lib, cls.lib.ERR_peek_error() == 0)
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 43, in _openssl_assert
    errors
cryptography.exceptions.InternalError: Unknown OpenSSL error. Please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this.

**Comment by reaperhulk** [comment] 2015-11-18 02:29
This error is a known issue for some users but we've been unable to isolate it. What version of OS X are you on, what Python are you using (system? it looks like system Python), and how did you install mitmproxy (via pip, easy_install, etc? Did you use sudo?)

**Comment by Tom4t0** [comment] 2015-11-18 02:33
```
sudo pip install mitmproxy

python
Python 2.7.10 (default, Aug 22 2015, 20:33:39)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.1)] on darwin

EI Captian 10.11.1
```

**Comment by reaperhulk** [comment] 2015-11-18 02:38
Do you happen to know where you got pip from? It's not present on an OS X install by default. (Failing that, could you provide the output of `pip --version` and `which pip`?)

**Comment by Tom4t0** [comment] 2015-11-18 02:39
```
➜  ~  which pip
/usr/local/bin/pip
➜  ~  pip --version
pip 7.1.2 from /Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg (python 2.7)
```

**Comment by reaperhulk** [comment] 2015-11-18 02:42
Thanks for the prompt responses. I'm just trying to replicate an environment similar to yours on this end :smiley: 

Another question: could you provide the output of `pip list`?

**Comment by Tom4t0** [comment] 2015-11-18 02:44
```
altgraph (0.10.2)
backports-abc (0.4)
backports.ssl-match-hostname (3.4.0.2)
bdist-mpkg (0.5.0)
beautifulsoup4 (4.4.1)
blinker (1.4)
bonjour-py (0.3)
certifi (2015.9.6.2)
cffi (1.3.0)
click (5.1)
ConfigArgParse (0.10.0)
construct (2.5.2)
CouchDB (1.0)
cryptography (1.1)
enum34 (1.0.4)
hpack (2.0.1)
html2text (2015.11.4)
httplib2 (0.9)
idna (2.0)
ipaddress (1.0.15)
ipcalc (1.1.3)
lxml (3.4.4)
macholib (1.5.1)
Mako (1.0.3)
MarkupSafe (0.23)
matplotlib (1.3.1)
mitmproxy (0.14.0)
modulegraph (0.10.4)
netlib (0.14.0)
NoSQLMap (0.5)
numpy (1.8.0rc1)
passlib (1.6.5)
pbkdf2 (1.3)
Pillow (3.0.0)
pip (7.1.2)
pocsuite (1.0.0.dev8)
prettytable (0.7.2)
py2app (0.7.3)
pyasn1 (0.1.9)
pycparser (2.14)
pycrypto (2.6.1)
pymongo (2.7.2)
pyobjc-core (2.5.1)
pyobjc-framework-Accounts (2.5.1)
pyobjc-framework-AddressBook (2.5.1)
pyobjc-framework-AppleScriptKit (2.5.1)
pyobjc-framework-AppleScriptObjC (2.5.1)
pyobjc-framework-Automator (2.5.1)
pyobjc-framework-CFNetwork (2.5.1)
pyobjc-framework-Cocoa (2.5.1)
pyobjc-framework-Collaboration (2.5.1)
pyobjc-framework-CoreData (2.5.1)
pyobjc-framework-CoreLocation (2.5.1)
pyobjc-framework-CoreText (2.5.1)
pyobjc-framework-DictionaryServices (2.5.1)
pyobjc-framework-EventKit (2.5.1)
pyobjc-framework-ExceptionHandling (2.5.1)
pyobjc-framework-FSEvents (2.5.1)
pyobjc-framework-InputMethodKit (2.5.1)
pyobjc-framework-InstallerPlugins (2.5.1)
pyobjc-framework-InstantMessage (2.5.1)
pyobjc-framework-LatentSemanticMapping (2.5.1)
pyobjc-framework-LaunchServices (2.5.1)
pyobjc-framework-Message (2.5.1)
pyobjc-framework-OpenDirectory (2.5.1)
pyobjc-framework-PreferencePanes (2.5.1)
pyobjc-framework-PubSub (2.5.1)
pyobjc-framework-QTKit (2.5.1)
pyobjc-framework-Quartz (2.5.1)
pyobjc-framework-ScreenSaver (2.5.1)
pyobjc-framework-ScriptingBridge (2.5.1)
pyobjc-framework-SearchKit (2.5.1)
pyobjc-framework-ServiceManagement (2.5.1)
pyobjc-framework-Social (2.5.1)
pyobjc-framework-SyncServices (2.5.1)
pyobjc-framework-SystemConfiguration (2.5.1)
pyobjc-framework-WebKit (2.5.1)
pyOpenSSL (0.13.1)
pyparsing (2.0.1)
pyperclip (1.5.24)
PySocks (1.5.6)
python-dateutil (1.5)
pytz (2013.7)
PyYAML (3.11)
redis (2.10.5)
requests (2.5.0)
scipy (0.13.0b1)
setuptools (1.1.6)
singledispatch (3.4.0.3)
six (1.4.1)
tornado (4.3)
urllib3 (1.12)
urwid (1.3.1)
virtualenv (13.1.2)
xattr (0.6.4)
zope.interface (4.1.1)
```


can you help me to slove this problem?

**Comment by reaperhulk** [comment] 2015-11-18 02:50
Thanks -- I've been able to reproduce this. We can finally investigate this more thoroughly.

For the moment the "easy" fix for you will be to `pip install cryptography==1.0.2`. Please note that this does *not* fix the underlying issue, but will work around it for your purposes for the moment.

**Comment by Tom4t0** [comment] 2015-11-18 02:52
thank you  

i sloved this problem :)

**Comment by reaperhulk** [comment] 2015-11-18 06:31
dupe of #2468

**Closed by reaperhulk** 2015-11-18 06:31 UTC
