### ISSUE TITLE
Discuss KDF usage with Fernet

### ISSUE THREAD

**Issue by wbond** [pyca/cryptography#2160] opened 2015-07-17 12:56 UTC
Based on #2159, it would probably make sense to mention using HKDF in the docs with Fernet. That way users who are trying to encrypt without using a key stored on disk somewhere have clear guidance.

**Comment by alex** [comment] 2015-07-17 13:04
Going to close this as a dupe of #1333. Thanks for bringing it up again!

**Comment by wbond** [comment] 2015-07-17 13:06
So while they are related, it seems that is issue is about writing code to handle user-provided keys, whereas this is about documentation. Does closing this mean you think it is a code issue, as opposed to a documentation issue?

**Comment by alex** [comment] 2015-07-17 13:09
I think that issue covers both topics.

**Comment by wbond** [comment] 2015-07-17 13:12
No, that issue doesn't talk about documentation related to using KDFs with Fernet. @reaperhulk mentions deciding if this is something cryptography wants to implement. That sounds like writing an API for password-based Fernet.

What I am proposing here is documentation about the fact that a KDF needs to be used with Fernet if the user is trying to use a password as the key.

Further, it seems to me that an issue like this should be fairly high priority, based on the comments on #1333 (blog posts with dangerous advice) and the goals of cryptography. Cryptography should be "Cryptography for humans." Based on that, I think that since Fernet is one of the few high-level layers in Cryptography, and that symmetric encryption using a password as the basis is fairly common, that this should be at least discussed in the documentation.

**Comment by alex** [comment] 2015-07-17 13:34
Ok. You've convinced me :-)

**Comment by wbond** [comment] 2015-07-17 14:40
I haven't used HKDF before, but from looking over the RFC right now, it doesn't appear to use an iteration count. That would be simpler than PBKDF2, however that means it is not stretching the key at all. If there is going to be documentation about using a password, it should use PBKDF2 instead since that stretches the key.

The other benefit of using PBKDF2 is that the ciphertext would not be very hard to decrypt in other environments since it would only be using well-known and highly-available algorithms.

I think the hardest part of documenting a simple process with PBKDF2 is going to be helping users determine an iteration count. The true correct number will be the highest number possible for a user's server. Perhaps a recommendation of starting at 20,000 and increasing until the process takes at least 100ms on a production server?

**Comment by reaperhulk** [comment] 2015-08-04 18:28
This is something we should do but not a blocker for release.

**Closed** 2015-08-30 16:48 UTC
Labels: documentation, recipes
