### ISSUE TITLE
X509 Verification

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#9812] opened 2023-11-01 18:10 UTC
Meta bug for those tracking this feature request.

refs https://github.com/pyca/cryptography/pull/8873

**Comment by woodruffw** [comment] 2023-11-01 18:24
Making an arbitrary comment so that this can be assigned to me 🙂

**Comment by alex** [comment] 2023-11-01 18:26
Closing as a dupe of https://github.com/pyca/cryptography/issues/2381

lol. lmao.

**Closed by alex** 2023-11-01 18:26 UTC
