### ISSUE TITLE
default_backend() fails on OS X El Capitan and Ubuntu (others?)

### ISSUE THREAD

**Issue by emonti** [pyca/cryptography#2907] opened 2016-05-10 23:50 UTC
I'm following the installation guide and my expectation is that a simple 'pip install cryptography' should work, however it does not appear to give me a working build since no backends are available?.

I have openssl installed via homebrew:

        ~/cryptotest brew install openssl
        Warning: openssl-1.0.2h already installed

Using a virtualenv:

        ~/cryptotest virtualenv venv
        New python executable in /Users/em/cryptotest/venv/bin/python2.7
        Also creating executable in /Users/em/cryptotest/venv/bin/python
        Installing setuptools, pip, wheel...done.
        ~/cryptotest . venv/bin/activate
        (venv) ~/cryptotest python --version
        Python 2.7.10

Install with pip 

        (venv) ~/cryptotest pip install --no-cache-dir cryptography
        Collecting cryptography
          Downloading cryptography-1.3.2-cp27-none-macosx_10_6_intel.whl (1.4MB)
            100% |████████████████████████████████| 1.4MB 89.5MB/s
        Requirement already satisfied (use --upgrade to upgrade): setuptools>=11.3 in ./venv/lib/python2.7/site-packages (from cryptography)
        Collecting enum34 (from cryptography)
          Downloading enum34-1.1.5-py2.py3-none-any.whl (61kB)
            100% |████████████████████████████████| 71kB 67.4MB/s
        Collecting ipaddress (from cryptography)
          Downloading ipaddress-1.0.16-py27-none-any.whl
        Collecting pyasn1>=0.1.8 (from cryptography)
          Downloading pyasn1-0.1.9-py2.py3-none-any.whl
        Collecting six>=1.4.1 (from cryptography)
          Downloading six-1.10.0-py2.py3-none-any.whl
        Collecting idna>=2.0 (from cryptography)
          Downloading idna-2.1-py2.py3-none-any.whl (54kB)
            100% |████████████████████████████████| 61kB 95.1MB/s
        Collecting cffi>=1.4.1 (from cryptography)
          Downloading cffi-1.6.0-cp27-cp27m-macosx_10_10_intel.whl (211kB)
            100% |████████████████████████████████| 215kB 103.4MB/s
        Collecting pycparser (from cffi>=1.4.1->cryptography)
          Downloading pycparser-2.14.tar.gz (223kB)
            100% |████████████████████████████████| 225kB 102.1MB/s
        Installing collected packages: enum34, ipaddress, pyasn1, six, idna, pycparser, cffi, cryptography
          Running setup.py install for pycparser ... done
        Successfully installed cffi-1.6.0 cryptography-1.3.2 enum34-1.1.5 idna-2.1 ipaddress-1.0.16 pyasn1-0.1.9 pycparser-2.14 six-1.10.0
        (venv) ~/cryptotest ipython
        WARNING: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
        Python 2.7.10 (default, Oct 23 2015, 19:19:21)
        Type "copyright", "credits" or "license" for more information.

        IPython 3.1.0 -- An enhanced Interactive Python.
        ?         -> Introduction and overview of IPython's features.
        %quickref -> Quick reference.
        help      -> Python's own help system.
        object?   -> Details about 'object', use 'object??' for extra details.

        In [1]: from cryptography.hazmat.backends import default_backend

        In [2]: default_backend()
        ---------------------------------------------------------------------------
        ValueError                                Traceback (most recent call last)
        <ipython-input-2-fcfa6195e3cc> in <module>()
        ----> 1 default_backend()

        /Users/em/cryptotest/venv/lib/python2.7/site-packages/cryptography/hazmat/backends/__init__.pyc in default_backend()
             33
             34     if _default_backend is None:
        ---> 35         _default_backend = MultiBackend(_available_backends())
             36
             37     return _default_backend

        /Users/em/cryptotest/venv/lib/python2.7/site-packages/cryptography/hazmat/backends/multibackend.pyc in __init__(self, backends)
             31         if len(backends) == 0:
             32             raise ValueError(
        ---> 33                 "Multibackend cannot be initialized with no backends. If you "
             34                 "are seeing this error when trying to use default_backend() "
             35                 "please try uninstalling and reinstalling cryptography."

        ValueError: Multibackend cannot be initialized with no backends. If you are seeing this error when trying to use default_backend() please try uninstalling and reinstalling cryptography.

        In [3]: import cryptography.hazmat.backends

        In [4]: cryptography.hazmat.backends._available_backends()
        Out[4]: []

I am on OS X El Capitan 10.11.4

**Comment by emonti** [comment] 2016-05-10 23:52
Tried installing without the wheel, same issue:

        (venv) ~/cryptotest env CRYPTOGRAPHY_OSX_NO_LINK_FLAGS=1 LDFLAGS="$(brew --prefix openssl)/lib/libssl.a $(brew --prefix openssl)/lib/libcrypto.a" CFLAGS="-I$(brew --prefix openssl)/include" pip install cryptography --no-cache-dir --upgrade --no-binary :all:
        Collecting cryptography
          Downloading cryptography-1.3.2.tar.gz (383kB)
            100% |████████████████████████████████| 389kB 18.4MB/s
        Requirement already up-to-date: idna>=2.0 in ./venv/lib/python2.7/site-packages (from cryptography)
        Requirement already up-to-date: pyasn1>=0.1.8 in ./venv/lib/python2.7/site-packages (from cryptography)
        Requirement already up-to-date: six>=1.4.1 in ./venv/lib/python2.7/site-packages (from cryptography)
        Requirement already up-to-date: setuptools>=11.3 in ./venv/lib/python2.7/site-packages (from cryptography)
        Requirement already up-to-date: enum34 in ./venv/lib/python2.7/site-packages (from cryptography)
        Requirement already up-to-date: ipaddress in ./venv/lib/python2.7/site-packages (from cryptography)
        Requirement already up-to-date: cffi>=1.4.1 in ./venv/lib/python2.7/site-packages (from cryptography)
        Requirement already up-to-date: pycparser in ./venv/lib/python2.7/site-packages (from cffi>=1.4.1->cryptography)
        Installing collected packages: cryptography
          Running setup.py install for cryptography ... done
        Successfully installed cryptography-1.3.2
        (venv) ~/cryptotest ipython
        WARNING: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
        Python 2.7.10 (default, Oct 23 2015, 19:19:21)
        Type "copyright", "credits" or "license" for more information.

        IPython 3.1.0 -- An enhanced Interactive Python.
        ?         -> Introduction and overview of IPython's features.
        %quickref -> Quick reference.
        help      -> Python's own help system.
        object?   -> Details about 'object', use 'object??' for extra details.

        In [1]: import cryptography.hazmat.backends

        In [2]: cryptography.hazmat.backends.default_backend()
        ---------------------------------------------------------------------------
        ValueError                                Traceback (most recent call last)
        <ipython-input-2-1393d3bc90c7> in <module>()
        ----> 1 cryptography.hazmat.backends.default_backend()

        /Users/em/cryptotest/venv/lib/python2.7/site-packages/cryptography/hazmat/backends/__init__.pyc in default_backend()
             33
             34     if _default_backend is None:
        ---> 35         _default_backend = MultiBackend(_available_backends())
             36
             37     return _default_backend

        /Users/em/cryptotest/venv/lib/python2.7/site-packages/cryptography/hazmat/backends/multibackend.pyc in __init__(self, backends)
             31         if len(backends) == 0:
             32             raise ValueError(
        ---> 33                 "Multibackend cannot be initialized with no backends. If you "
             34                 "are seeing this error when trying to use default_backend() "
             35                 "please try uninstalling and reinstalling cryptography."

        ValueError: Multibackend cannot be initialized with no backends. If you are seeing this error when trying to use default_backend() please try uninstalling and reinstalling cryptography.

**Comment by emonti** [comment] 2016-05-10 23:57
... and same issue on Linux

```
...
Successfully installed cryptography idna pyasn1 six setuptools enum34 ipaddress cffi pycparser
Cleaning up...
(venv)em@apt-dev-01:~/cry$
(venv)em@apt-dev-01:~/cry$ ipython
WARNING: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
Type "copyright", "credits" or "license" for more information.

IPython 4.1.2 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import cryptography.hazmat.backends

In [2]: cryptography.hazmat.backends._available_backends()
Out[2]: []

In [3]: cryptography.hazmat.backends.default_backend()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-1393d3bc90c7> in <module>()
----> 1 cryptography.hazmat.backends.default_backend()

/home/em/cry/venv/lib/python2.7/site-packages/cryptography/hazmat/backends/__init__.pyc in default_backend()
     33
     34     if _default_backend is None:
---> 35         _default_backend = MultiBackend(_available_backends())
     36
     37     return _default_backend

/home/em/cry/venv/lib/python2.7/site-packages/cryptography/hazmat/backends/multibackend.pyc in __init__(self, backends)
     31         if len(backends) == 0:
     32             raise ValueError(
---> 33                 "Multibackend cannot be initialized with no backends. If you "
     34                 "are seeing this error when trying to use default_backend() "
     35                 "please try uninstalling and reinstalling cryptography."

ValueError: Multibackend cannot be initialized with no backends. If you are seeing this error when trying to use default_backend() please try uninstalling and reinstalling cryptography.

In [4]: quit
u(venv)em@apt-dev-01:~/cry$ uname -a
Linux apt-dev-01 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
(venv)em@apt-dev-01:~/cry$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
(venv)em@apt-dev-01:~/cry$ python --version
Python 2.7.6
```

**Comment by emonti** [comment] 2016-05-11 00:05
I started going back in versions - looks like this broke in 1.3 -- 1.2.3 works.

**Comment by reaperhulk** [comment] 2016-05-11 21:35
This is quite odd (and I can't replicate it). Out of curiosity: what happens if you install ipython inside the virtualenv instead of trying to use the global one?

**Comment by emonti** [comment] 2016-05-11 21:47
Good intuition! It works if i install and run ipython in the virtualenv.
```
(venv) ~/cry ./venv/bin/ipython
Python 2.7.10 (default, Nov  2 2015, 09:52:41)
Type "copyright", "credits" or "license" for more information.

IPython 4.2.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from cryptography.hazmat.backends import default_backend

In [2]: default_backend()
Out[2]: <cryptography.hazmat.backends.multibackend.MultiBackend at 0x104cfe750>

```

Confirmed on OS X El Capitan and Ubuntu 14.04

**Comment by emonti** [comment] 2016-05-11 21:52
So yea, thanks for the help. I'm not sure this is cryptography's bug (or actually a bug at all since iPython even suggested I try this too and I totally ignored it). I'll leave it open incase you want to investigate it further, but if you don't, feel free to close this issue.

**Comment by alex** [comment] 2016-05-11 21:58
Going to close this, since I strongly suspect there's nothing we can do to improve it.

**Closed by alex** 2016-05-11 21:58 UTC

**Comment by fukanchik** [comment] 2016-06-27 20:09
I am having the same problem. cryptography installed into /usr/lib/site-packages does not work with the same exception, installing it into ~/.local  works fine.

In my case this is caused by the ghost directories of old versions:

ls -dU /opt/python-3.4/lib/python3.4/site-packages/
- cryptography-1.2.3-py3.4.egg-info
- cryptography-1.3.1-py3.4.egg-info
- cryptography-1.4-py3.4.egg-info

directories cryptography-1.2.3-py3.4.egg-info  cryptography-1.3.1-py3.4.egg-info are empty. Only 1.4 contains files.

...and seems pkg_resources just selects the first one in the directory order (in my case 1.2.3) :

https://github.com/pypa/setuptools/blob/4950c05901da4382741cc8ce22a12da50436e2cf/pkg_resources/__init__.py#L1971

easy check:
$ pip freeze
cryptography==1.2.3
...

it returns 1.2.3 which is empty and ==>
`pkg_resources.iter_entry_points(
                "cryptography.backends"
            )`
returns nothing and ==> no backends found

**Comment by snahil** [comment] 2019-03-28 11:38
i think this issue  is due to DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
