### ISSUE TITLE
EVP_CipherUpdate issue

### ISSUE THREAD

**Issue by philippj** [pyca/cryptography#2917] opened 2016-05-21 17:18 UTC
I ran into an issue while trying to update the evp cipher.

```
Traceback (most recent call last):
  File "#", line 67, in symmetric_encrypt_with_iv
    cyphertext = encryptor.update(pad(message)) + encryptor.finalize()
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/primitives/ciphers/base.py", line 137, in update
    return self._ctx.update(data)
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 117, in update
    len(data))
TypeError: initializer for ctype 'unsigned char *' must be a str or list or tuple, not unicode
```

Iam using python 2.7.3. Cryptography is up to date.

```
Requirement already up-to-date: cryptography in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: idna>=2.0 in /usr/local/lib/python2.7/dist-packages (from cryptography)
Requirement already up-to-date: pyasn1>=0.1.8 in /usr/local/lib/python2.7/dist-packages (from cryptography)
Requirement already up-to-date: six>=1.4.1 in /usr/local/lib/python2.7/dist-packages (from cryptography)
Requirement already up-to-date: setuptools>=11.3 in /usr/local/lib/python2.7/dist-packages (from cryptography)
Requirement already up-to-date: enum34 in /usr/local/lib/python2.7/dist-packages (from cryptography)
Requirement already up-to-date: ipaddress in /usr/local/lib/python2.7/dist-packages (from cryptography)
Requirement already up-to-date: cffi>=1.4.1 in /usr/local/lib/python2.7/dist-packages (from cryptography)
Requirement already up-to-date: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.4.1->cryptography)
```

**Comment by alex** [comment] 2016-05-21 17:20
Can you provide code to reproduce this issue? From the traceback it looks like you are passing `unicode` to `update()`, as documented, `update()` takes a `bytes` argument, not `unicode`.

(Closing the issue until there's clear reproducing instructions, if those are added I'll reopen)

**Closed by alex** 2016-05-21 17:20 UTC

**Comment by philippj** [comment] 2016-05-21 18:48
```
def symmetric_encrypt(message, key):
    iv = random_bytes(16)
    return symmetric_encrypt_with_iv(message, key, iv)

def symmetric_encrypt_with_iv(message, key, iv):
    encrypted_iv = symmetric_encrypt_iv(iv, key)
    encryptor =  Cipher(AES(key), CBC(iv), backend).encryptor()
    cyphertext = encryptor.update(pad(message)) + encryptor.finalize()
    return encrypted_iv + cyphertext

loginkey = symmetric_encrypt(username, sessionKey)
```

`username` is a 6-24 char string, `sessionKey` is a random string

Thank you for the quick reply.

**Comment by reaperhulk** [comment] 2016-05-21 21:49
@philippj the provided code doesn't actually demonstrate the issue. Verify that the iv, key, and result of `pad(message)` are all bytes and not unicode strings.
