### ISSUE TITLE
[Feature request / help] Delete private key (modulus) from memory (or locate it in memory and manually zero it)?

### ISSUE THREAD

**Issue by RSchmitzHH** [pyca/cryptography#5667] opened 2020-12-23 12:52 UTC
I'd like to delete the _RSAPrivateKey object, or at least its modulus, from the memory (which is related to issue #4551 that I want to support). 

Browsing the documentation and the sources, I cannot find any built-in method to do so. Have I overlooked something or is this still the case? 

If it is still the case, is there a possibility to find the immutable object that stores the private key modulus so that I can manually zero it using ctypes.memset as a workaround? And: Would you consider adding a built-in method for deletion of private keys?

**Comment by alex** [comment] 2020-12-23 13:39
This is a duplicate of https://github.com/pyca/cryptography/issues/4551.

It's also documented as a limitation already: https://cryptography.io/en/latest/limitations.html#secure-memory-wiping

**Closed by alex** 2020-12-23 13:39 UTC

**Comment by RSchmitzHH** [comment] 2020-12-23 13:56
So why not retrieve the immutable that holds the modulus and manually zero it? (As in http://web.archive.org/web/20100929111257/http://www.codexon.com/posts/clearing-passwords-in-memory-with-python for strings?)

**Comment by tiran** [comment] 2020-12-23 14:04
That recipe is not sufficient. It only wipes one locations. Your sensitive payload is likely kept in multiple locations on the heap and on the stack.

**Comment by RSchmitzHH** [comment] 2020-12-23 14:08
You're right, that's true... Though, can you tell me where _RSAPrivateKey stores it so that I can wipe at least the most obvious location(s)? Many thanks!
