### ISSUE TITLE
AESGCM should accept arbitrary tag lengths, similar to AESCCM

### ISSUE THREAD

**Issue by PeterAdamson** [pyca/cryptography#6107] opened 2021-06-10 14:32 UTC
For NIST test vectors, it is required that decryption functionality for AESGCM accommodate tag lengths of 4, 6, 8, etc, as opposed to just 16.  I propose that AESGCM should be modified to match the AESCCM functionality.  

The current AESGCM class looks as follows:

```
class AESGCM(object):
    _MAX_SIZE = 2 ** 32

    def __init__(self, key):
        utils._check_bytes("key", key)
        if len(key) not in (16, 24, 32):
            raise ValueError("AESGCM key must be 128, 192, or 256 bits.")

        self._key = key

    @classmethod
    def generate_key(cls, bit_length):
        if not isinstance(bit_length, int):
            raise TypeError("bit_length must be an integer")

        if bit_length not in (128, 192, 256):
            raise ValueError("bit_length must be 128, 192, or 256")

        return os.urandom(bit_length // 8)

    def encrypt(self, nonce, data, associated_data):
        if associated_data is None:
            associated_data = b""

        if len(data) > self._MAX_SIZE or len(associated_data) > self._MAX_SIZE:
            # This is OverflowError to match what cffi would raise
            raise OverflowError(
                "Data or associated data too long. Max 2**32 bytes"
            )

        self._check_params(nonce, data, associated_data)
        return aead._encrypt(
            backend, self, nonce, data, associated_data, 16
        )

    def decrypt(self, nonce, data, associated_data):
        if associated_data is None:
            associated_data = b""

        self._check_params(nonce, data, associated_data)
        return aead._decrypt(
            backend, self, nonce, data, associated_data, 16
        )

    def _check_params(self, nonce, data, associated_data):
        utils._check_bytes("nonce", nonce)
        utils._check_bytes("data", data)
        utils._check_bytes("associated_data", associated_data)
        if len(nonce) == 0:
            raise ValueError("Nonce must be at least 1 byte")
```

I propose that it be modified to the following:

```
class AESGCM(object):
    _MAX_SIZE = 2 ** 32

    def __init__(self, key, tag_len=16):
        utils._check_bytes("key", key)
        if len(key) not in (16, 24, 32):
            raise ValueError("AESGCM key must be 128, 192, or 256 bits.")
        self.tag_len = tag_len
        self._key = key

    @classmethod
    def generate_key(cls, bit_length):
        if not isinstance(bit_length, int):
            raise TypeError("bit_length must be an integer")

        if bit_length not in (128, 192, 256):
            raise ValueError("bit_length must be 128, 192, or 256")

        return os.urandom(bit_length // 8)

    def encrypt(self, nonce, data, associated_data):
        if associated_data is None:
            associated_data = b""

        if len(data) > self._MAX_SIZE or len(associated_data) > self._MAX_SIZE:
            # This is OverflowError to match what cffi would raise
            raise OverflowError(
                "Data or associated data too long. Max 2**32 bytes"
            )

        self._check_params(nonce, data, associated_data)
        return aead._encrypt(
            backend, self, nonce, data, associated_data, self.tag_len
        )

    def decrypt(self, nonce, data, associated_data):
        if associated_data is None:
            associated_data = b""

        self._check_params(nonce, data, associated_data)
        return aead._decrypt(
            backend, self, nonce, data, associated_data, self.tag_len
        )

    def _check_params(self, nonce, data, associated_data):
        utils._check_bytes("nonce", nonce)
        utils._check_bytes("data", data)
        utils._check_bytes("associated_data", associated_data)
        if len(nonce) == 0:
            raise ValueError("Nonce must be at least 1 byte")
```

I have tested this with the following NIST test vector using a tag_len of 8, and it works:

        "tgId": 22,
        "testType": "AFT",
        "direction": "decrypt",
        "keyLen": 128,
        "ivLen": 640,
        "ivGen": "internal",
        "ivGenMode": "8.2.1",
        "payloadLen": 992,
        "aadLen": 288,
        "tagLen": 64,
            "tcId": 317,
            "key": "724E0631E820B5EB4B176703BE56AEBF",
            "aad": "7F2362C0CC18F28089D1FDCE952D58EDCCC1946372427DFE0E840124D1D91167BFBFF818",
            "iv": "15EB8BD4A73CE1D3BACB22689ACE2BC505CCE2773B78AC58EC9ABC6AA4B79AB795F2BBF7879A2F55BAB876BBDCEDBF8E43B61F59768D0AD1E3126ED7919B8C3186FE55595C6F7C2426590445498F6A5B",
            "ct": "507F328A12B19B527FC75F971E1C7AC79D35DD0478F8C3F82F9F334DB706808C761D2AABE86E2872AFC167F0968511F00E0D6C95D7006766BAF4570D9E818693AD35FD5135EEC43669D0ADE46FA58CCD3E2174ADA5E5A2D0694B38AD5A64860271A860B954644E6FEE9956C6CE9EFAB113ED7C3D08DD9AF0324A2A29",
            "tag": "417088F3461034B1"

**Comment by PeterAdamson** [comment] 2021-06-10 14:35
Note that I have only tested this for the decrypt functionality, as tag length has no implications for encryption related to NIST test vectors (i.e. in encryption if the test vector asks for 8 byte tag, I can trim 8 bytes off the 16 bit generated tag to get the correct tag)

**Comment by alex** [comment] 2021-06-10 14:45
Is there a real world use case for this?

We currently use the NIST vectors in our tests and simply trim them down to only include teh the ones with the right tag lengths.

**Comment by PeterAdamson** [comment] 2021-06-10 14:50
That's a good question and I'm not sure.  However, this is functionality that pycryptodome has (which we can't use for test vectors since it doesn't use openssl).  It's also functionality that the c implementation of OpenSSL with the EVP interface has.  It seems like this library is in the minority with hardcoding the length at 16

**Comment by reaperhulk** [comment] 2021-06-10 14:58
I believe we did this because we wanted the AEAD modyle version of GCM to be as strong as possible. We have a separate GCM mode primitive that can be used with the cipher construct that allows truncation of tag length. CCM allows truncation in its AEAD module class because we have no primitive CCM mode equivalent.

**Comment by PeterAdamson** [comment] 2021-06-10 15:02
Could you point me in the direction of that primitive or a code sample?

**Comment by alex** [comment] 2021-06-10 15:02
https://cryptography.io/en/latest/hazmat/primitives/symmetric-encryption/#cryptography.hazmat.primitives.ciphers.modes.GCM

It's also worth noting that the security of decreasing tag sizes is much larger than many people realize, and threatens not just integrity but also confidentiality.

I'm going to close this, this is working as intended.

**Closed by alex** 2021-06-10 15:02 UTC

**Comment by reaperhulk** [comment] 2021-06-10 15:32
One note, if the docs should more prominently or clearly state that this class exists and allows additional flexibility for those who require it then I’d be happy to review a PR that improves that! This issue suggests we haven’t hit the mark in the docs.
