### ISSUE TITLE
version 37.0.3 with pysftp causes a malloc/free error, but not 37.0.2

### ISSUE THREAD

**Issue by tommyjcarpenter** [pyca/cryptography#7367] opened 2022-06-22 11:55 UTC
Unfortunately, I have little logs to give info here on, since our kubernetes container just dies and there are no python logs :(

We have an application that uses pysftp/durasftp, which depends on this package. 

On version 37.0.2, everything is fine. 
When our requirements.txt upgraded to 37.0.3, our containers crash during SFTPing with:

```
[2022-06-22 11:19:27,397] [req-id:607a04ca21c44ee3a52b2d6d0cbbb5c2] [dissapi.sftp] [DEBUG] [7] Attempting to connect to sftp.xxx.com using user xxx on port 22. Other options, subdir: None, confirm: False.
!!! uWSGI process 7 got Segmentation Fault !!!
malloc(): corrupted top size
Aborted (core dumped)
```

*Neither pysftp/durasftp* versions changed. Keeping those constants at:
```
durasftp==1.0.0
pysftp==0.2.9
```

Pinning only `cryptography` in our requirements to 37.0.2, everything is fine, with those package versions. Changing to the latest, 0.3, causes our containers to be executed with the above. 

Any ideas? Sorry I don't have more logs 😢

**Comment by alex** [comment] 2022-06-22 11:57
This looks like it's the same as https://github.com/pyca/pyopenssl/issues/1129

**Comment by alex** [comment] 2022-06-22 12:02
Seems very likely that this is: https://github.com/openssl/openssl/issues/18625

I _assume_ OpenSSL will issue a new security release very shortly fixing this. I hope.

**Comment by tommyjcarpenter** [comment] 2022-06-22 12:08
Thank you for your hard work and quick reply, Alex.

Half my pain was just pinning this down in our application. Took me awhile to understand what the heck was happening.

**Comment by alex** [comment] 2022-06-22 12:13
Ok, we have yanked the 37.0.3 due to this regression. Hopefully in a day or two we'll issue a 37.0.4. Going to close this since it should be resolved for now.

**Closed by alex** 2022-06-22 12:13 UTC
