### ISSUE TITLE
cryptography.exceptions.InternalError: Unknown OpenSSL error.

### ISSUE THREAD

**Issue by SecUpwN** [pyca/cryptography#2727] opened 2016-02-20 20:03 UTC
Good evening @pyca, I am running [openSUSE Tumbleweed](https://en.opensuse.org/Portal:Tumbleweed) and enjoyed configuring and running the simple [torbrowser-launcher](https://github.com/micahflee/torbrowser-launcher) by @micahflee. I am not quite sure what happened and why, but all of a sudden `torbrowser-launcher` refuses to run. Could it be that some upgrades broke something important? Please help me to determine and solve the error in this [logfile](https://defuse.ca/b/XAvO1o5s). Thanks for having a look at it!

**Comment by alex** [comment] 2016-02-20 20:04
Please include a full traceback, as well as what versions of things you are running.

**Comment by SecUpwN** [comment] 2016-02-20 21:28
>Please include a full traceback, as well as what versions of things you are running.

Thanks for assisting, @alex. Please tell me the command how to log the full stacktrace and versions.

**Comment by SecUpwN** [comment] 2016-02-20 23:52
>Please help me to determine and solve the error in this [logfile](https://defuse.ca/b/XAvO1o5s).

**Comment by reaperhulk** [comment] 2016-02-20 23:57
The listed error decodes to `'error:0200100D:system library:fopen:Permission denied'`. Error messages of this nature are typically something else using OpenSSL in the same process space and not clearing the error stack before cryptography attempts to initialize.

**Comment by SecUpwN** [comment] 2016-02-21 12:08
>Error messages of this nature are typically something else using OpenSSL in the same process space and not clearing the error stack before cryptography attempts to initialize.

That means? The strange thing is that it worked perfectly before. What to do now to fix this error?

**Comment by alex** [comment] 2016-02-21 21:17
Before what?

You probably should report this bug to whatever software you're using, rather than to cryptography. Since the error you indicated is not caused by cryptography, I'm going to close this issue.

**Closed by alex** 2016-02-21 21:17 UTC
