### ISSUE TITLE
cffi version mismatch installing cryptography

### ISSUE THREAD

**Issue by ianloic** [pyca/cryptography#2491] opened 2015-11-23 22:16 UTC
pip install -t lib/ cryptography

Gives me:

    AssertionError: version mismatch, 1.3.0 != 1.3.1

apparently due to cffi versioning. `pip install cffi` does work.

Full log [here](https://github.com/pyca/cryptography/files/42093/log.txt).

**Comment by reaperhulk** [comment] 2015-11-23 22:31
This appears to be a problem with the way cffi is upgrading via pip/setuptools and not anything directly related to cryptography (which only requires `>=1.1.0`). /cc @dstufft as I'm guessing he'll know what happened here.

**Comment by alex** [comment] 2015-11-23 23:45
Hey Ian!

Does this reproduce if you drop the `-t lib/`?

**Comment by ianloic** [comment] 2015-11-24 19:12
Hey Alex, it seems to. :(

**Comment by dstufft** [comment] 2015-11-24 19:25
@ianloic What OS are you running this on?

**Comment by ianloic** [comment] 2015-11-24 19:44
Debian unstable.

**Comment by dstufft** [comment] 2015-11-24 20:02
Ok. I've reproduced the error and I know why it happens.

Basically, the CFFI library ships a single package on PyPI which has both build time and runtime components and there is a strict requirement that the two versions match. Debian has taken that single library and split it into two pieces, the build time and runtime components and made it so that you can install *only* the runtime component without the build time component.

Then what happens is when pip attempts to install cryptography it downloads the CFFI from PyPI (which is now a newer version of CFFI than what you have in Debian unstable) and installs it. Then when it attempts to actually import it, it gets the runtime components from Debian but the build time components from PyPI which are not compatible and it blows up.

The quick fix is to run ``apt-get install python-cffi`` to also install the build time components from Debian so pip won't attempt to install them from PyPI. The longer term fix is going to require talking to Debian and figuring out what (if anything) they want to do about it.

**Comment by reaperhulk** [comment] 2015-12-02 04:48
Closing this since it's not an issue cryptography can control -- I'd suggest raising this with Debian with Donald's information so they can start thinking about what (if anything) they want to do.

**Closed by reaperhulk** 2015-12-02 04:48 UTC

**Comment by j10sanders** [comment] 2016-10-23 00:19
Very helpful, thank you @dstufft
