### ISSUE TITLE
Could not deserialize key data

### ISSUE THREAD

**Issue by shaaaarpy** [pyca/cryptography#4962] opened 2019-07-29 18:40 UTC
serialization.load_pem_private_key function always throws the value error could not deserialize data with python 3.6. It works well with python 2.7

**Comment by alex** [comment] 2019-07-29 18:48
Can you give us more details? What version of cryptography? How can we reproduce this? Can you give us a full stack trace?

**Comment by shaaaarpy** [comment] 2019-07-29 18:53
Hi alex
I am using cryptography==2.7 with python 3.6.8
My code is  
  
 with open(creds.SIGNING_PEM_FILE_PATH, 'rb') as key_file:
        private_key = serialization.load_pem_private_key(
            (key_file.read()),
            password=None,
            backend=default_backend())

The error i am getting is :
File "/opt/python/cryptography/hazmat/backends/openssl/backend.py", line 1335, in _handle_key_loading_error
raise ValueError("Could not deserialize key data.")

I have tried multiple online solutions but none is working.
Thank you

**Comment by shaaaarpy** [comment] 2019-07-29 19:27
![image](https://user-images.githubusercontent.com/23281566/62076316-fea1c880-b264-11e9-84d5-8a6ed47cddee.png)
For the complete traceback please have a look
Thank you

**Comment by Hondsome** [comment] 2019-07-31 09:19
I also came this problem. maybe problom is that here ? 

    def _handle_key_loading_error(self):
        errors = self._consume_errors()

        if not errors:
            raise ValueError("Could not deserialize key data.")

**Comment by shaaaarpy** [comment] 2019-07-31 09:28
Hi Hondsome,
So did you solve this problem?

Thank you

**Comment by Hondsome** [comment] 2019-07-31 09:36
> Hi Hondsome,
> So did you solve this problem?
> 
> Thank you

No, I am trying

**Comment by Hondsome** [comment] 2019-07-31 12:18
> Hi Hondsome,
> So did you solve this problem?
> 
> Thank you

i solve that , uninstall cryptography  2.6 and install cryptography==2.2   . it worked

**Comment by shaaaarpy** [comment] 2019-07-31 12:22
Thanks a lot Hondsome. Just to confirm python version is 3 right?

**Comment by Hondsome** [comment] 2019-07-31 12:45
hhh,no . i use 2.7 .  maybe is cryptography version problem , just try it.   i solve my problem

**Comment by cpj2195** [comment] 2019-07-31 16:36
@alex the Problem is coming up on AWS lambda but is working fine with python3.6 on local ubuntu system. Can you help us a bit here, we are stuck on this problem for quite a few days now. 
P.S I'm @shaaaarpy 's colleague.

**Comment by strickon** [comment] 2020-04-20 17:30
> @alex the Problem is coming up on AWS lambda but is working fine with python3.6 on local ubuntu system. Can you help us a bit here, we are stuck on this problem for quite a few days now.
> P.S I'm @shaaaarpy 's colleague.

Did you ever resolve it?  I am facing the same issue.  What was the solution?

**Comment by alex** [comment] 2020-04-20 17:57
Without clear instructions to reproduce this issue, there's not much we can do.

**Comment by reaperhulk** [comment] 2020-04-20 17:58
Different versions of OpenSSL can be picky about key formats. If you're seeing it work in one env but not another take a hard look at the key and make sure it's a valid PEM: https://cryptography.io/en/latest/faq/#why-can-t-i-import-my-pem-file

I'm going to close this since it's too generic but if you have a reproducer or can provide a sample key (that isn't used in your system!!!) that demonstrates the problem we can take a look. Please open a new issue for it :)

**Closed by reaperhulk** 2020-04-20 17:58 UTC

**Comment by Valerialukaj** [comment] 2020-06-02 10:22
I have the same problem, but I can't even solve it with the change of the library version. Anyone have any ideas?
