### ISSUE TITLE
Problem with setup.py

### ISSUE THREAD

**Issue by guenhter** [pyca/cryptography#3142] opened 2016-09-06 13:22 UTC
When running the installation for ansible, I get an installation error:

```
Running setup.py install for cryptography

    Installed /tmp/pip-build-nYlRoP/cryptography/cffi-1.8.2-py2.7-linux-x86_64.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-nYlRoP/cryptography/setup.py", line 334, in <module>
        **keywords_with_side_effects(sys.argv)
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 266, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 301, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
        ['__name__'])
    ImportError: No module named setuptools_ext
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-nYlRoP/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-8ng9DG-record/install-record.txt --single-version-externally-managed --compile:


Installed /tmp/pip-build-nYlRoP/cryptography/cffi-1.8.2-py2.7-linux-x86_64.egg

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip-build-nYlRoP/cryptography/setup.py", line 334, in <module>

    **keywords_with_side_effects(sys.argv)

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 266, in __init__

    _Distribution.__init__(self,attrs)

  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__

    self.finalize_options()

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 301, in finalize_options

    ep.load()(self, ep.name, value)

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load

    ['__name__'])

ImportError: No module named setuptools_ext

----------------------------------------
  Can't roll back cryptography; was not uninstalled
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-nYlRoP/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-8ng9DG-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-nYlRoP/cryptography
Storing debug log for failure in /root/.pip/pip.log
```

Steps to reproduce:
1. `docker run -it debian:8`
2. `apt-get update`
3. `apt-get install -y python-pip python-dev build-essential libssl-dev libffi-dev`
4. `pip install paramiko PyYAML Jinja2`

**Comment by Ayrx** [comment] 2016-09-06 13:33
What version of CFFI do you have? Try doing a `pip install -U cffi` and see if that resolves the issue.

**Comment by alex** [comment] 2016-09-06 13:34
Duplicate of it, appears to be caused by mixing system/pip cffis https://github.com/pyca/cryptography/issues/2348

**Closed by alex** 2016-09-06 13:34 UTC

**Comment by guenhter** [comment] 2016-09-06 15:33
I tried `pip install -U cffi` but than I'm not even able to execute `pip --version`
