### ISSUE TITLE
Type error in x509/name.py

### ISSUE THREAD

**Issue by oflebbe** [pyca/cryptography#4044] opened 2017-12-06 20:36 UTC
Version of python: python2.7 (Error can be reproduced on fedora26 or debian9)

importing x509 module (as done for instance by pyOpenSSL) results in a 

> TypeError: 'type' object is not iterable

As far I can see it is the result of this sniplet 
`from __future__ import absolute_import, division, print_function

from enum import Enum

class _ASN1Type(Enum):
    UTF8String = 12
    NumericString = 18
    PrintableString = 19
    T61String = 20
    IA5String = 22
    UTCTime = 23
    GeneralizedTime = 24
    VisibleString = 26
    UniversalString = 28
    BMPString = 30

_ASN1_TYPE_TO_ENUM = dict((i.value, i) for i in _ASN1Type)`

in name.py . Running this code will result in the mentioned error code

**Comment by alex** [comment] 2017-12-06 20:39
This isn't a SyntaxError.

This is because you have the incompatible `enum` package installed, not the `enum34` which our `setup.py` specifies. 

Closing as a dupe of #4010

**Closed by alex** 2017-12-06 20:39 UTC

**Comment by oflebbe** [comment] 2017-12-06 20:41
Wow that was quick, thanks for the tip!
