### ISSUE TITLE
Document how to write and install optional backends

### ISSUE THREAD

**Issue by Ayrx** [pyca/cryptography#704] opened 2014-03-01 17:58 UTC
There might be an issue of code bloat if/when we start adding support for other SSL libraries in the future. I don't really think it's a good idea to force the users to pull down and install bindings for gcrypt/gnutls/polarssl etc if he is just interested in using the OpenSSL backend for example.

Perhaps we should find and document a "fixed" way of writing and installing optional backends in a way that the user can install separately from the main codebase? 

Thoughts?

**Comment by Commod0re** [comment] 2015-06-11 06:18
That would actually be great - I would be happy to at least help implement a separate gcrypt backend to cover a handful of things that are not provided by OpenSSL that would be nice for PGPy (such as ElGamal encryption/decryption)

**Comment by reaperhulk** [comment] 2015-06-11 13:18
One of our biggest challenges here is that we have no good way to make openssl an optional backend yet, so anyone installing an alternate backend would still need to have the openssl one present at the moment.

Additionally, testing is a problem (do you add missing features as classes in the separate package? If so, what happens when two backends implement that feature?). We're going to get to this, but this is likely to be a longer term issue.

**Comment by Commod0re** [comment] 2015-06-11 22:41
Oh, yeah, I definitely understand this is a Hard Problem™ and I'm not expecting it to come along soon (it's not of critical importance to me), but it does nonetheless have my interest.

As for needing to have the openssl one present, I am perfectly okay with that as a requirement as a user of the library. I am somewhat more averse to needing to install two completely separate crypto libraries to be able to implement things that are currently not available in Cryptography (e.g. ElGamal and Twofish, which I could technically use PyCrypto to implement, but that introduces other issues and a larger dependency requirement for my own users.

As for the missing features problem, my initial thought was to provide the interface here, even if OpenSSL doesn't necessarily provide it (sorta like how the CommonCrypto backend can only currently be used to handle a subset of all the features available), which could prevent the problem of clashing classnames. I do also see how that complicates testing. How can you make any guarantees about an interface that you can't even test using the default backend?

Here's one potential answer that eases the onus on you guys somewhat:

 - Provide the ability to define additional interfaces for features that do not exist in the default backend, and show how to write an implementation for that interface

 - Additionally, provide some class naming guidance. Strongly suggest that people doing so prefix their interface class names with something specific to their package to prevent clashing on a system where multiple backends providing the same missing feature are installed. Then, if/when the feature itself becomes available in the main library, their implementations still won't clash, they can then also provide for the canonical interface at their leisure.

   Alternately, suggest that people find others who are or have implemented the same feature and cooperate enough to provide consistent interfaces, so it wouldn't matter if one or both are installed. That does require a little more care on our part than yours, so it may not turn out to be a very feasible option.

To me, at least, that seems like a fairly reasonable way to solve that particular piece of the puzzle. Hopefully it helps a little, but if not, no worries. :)

**Comment by Ayrx** [comment] 2015-06-11 22:55
Michael,
The ability to add additional backends is already present in the library,
if somewhat undocumented. The unsolved issues are related to our testing
infrastructure and how to maintain 100% coverage and if/how to make OpenSSL
optional.
I think most of the devs on this project share the opinion that we should
not be providing interfaces for which there are no "officially supported"
backends for.

**Comment by Commod0re** [comment] 2015-06-11 23:39
Yeah, I understand that the ability to do so is already *technically* present, but is it possible to reasonably add interfaces for things (ciphers and key formats, especially) that do not currently exist in the core library? Are there additional hoops I would need to jump through to ensure that any of that could even work? Is there documentation already available somewhere that might shed some light on how to even get started? Even if there is no documentation yet, does the alluded to "fixed way" of doing this stuff exist already in any form? If someone were to start working on one now, would any significant portion of that work be invalidated by changes made in the meantime? When a feature like this is mostly undocumented, that indicates to me that the way it works is probably still in flux, or is at least not what the implementers would deem "presentable" for whatever reason.

If you've already got all that stuff figured out, then as I said, feel free to disregard my suggestion. If that is indeed the case, it was not apparent to me. I was merely trying to help. There was no prior indication that it was unwelcome in this case, so I'm sorry.

> I think most of the devs on this project share the opinion that we should not be providing interfaces for which there are no "officially supported" backends for.

Indeed, and as I said, that is totally reasonable. I wouldn't expect you to provide interfaces that you don't also provide a concrete implementation for. I hope that was clear from my previous comment.

**Comment by Ayrx** [comment] 2015-06-11 23:41
Michael,

You misunderstood my comment. I was not trying to be hostile in any manner.
:)


I'm just pointing out that we technically *can* already do so, there's just
some work we need to do before we can document and officially support it.

**Comment by alex** [comment] 2016-09-17 01:09
Closing as a dupe of #858

**Closed by alex** 2016-09-17 01:09 UTC
Labels: administrative, documentation
