### ISSUE TITLE
Cryptography wheels since 1.9 lack legacy ciphers (RC4, 3DES), causes undebuggable breakage for downstream users

### ISSUE THREAD

**Issue by benjolitz** [pyca/cryptography#4087] opened 2018-01-16 23:27 UTC
This has eaten a few days of my time. Suffice to say, it began in scrapy/scrapy#3065 , went to requests/requests#4458 where the destination server was blamed despite it being accessible from curl, Chrome, ${insert browser here}, openssl (system and brewed), et al.

I ended up debugging by pyOpenSSL SSL.Context, SSL.Connection to figure out why I got two different cipher lists independent of my OpenSSL installations. Very, very difficult to debug.

Long story short, the binary assets distributed for OSX (I can confirm), possibly Windows (requests/requests#1308), and definitely Linux lack 3DES, RC4, etc ciphers necessary for `context.set_cipher_list` to actually work for legacy websites as documented by Scrapy, Requests.

I discovered this after removing cryptography and reinstalling from source via `CPPFLAGS=-I/usr/local/opt/openssl/include LDFLAGS=-L/usr/local/opt/openssl/lib pip install --no-binary cryptography cryptography`

I determined that the earliest working version of cryptography that worked with DES ciphers for HTTPS negotiation was 1.8 (throwing an invalid cert error that is easily bypassed by ignoring cert validation).

Steps to reproduce (Amazon AMI) 

0. Get a Python3.6 installation with all the development trimmings (`yum install openssl-devel python-devel`)
```
(sudo rm -rf /tmp/cpython3.6-build || true) && mkdir /tmp/cpython3.6-build && \
    cd /tmp/cpython3.6-build && \
    curl https://www.python.org/ftp/python/3.6.1/Python-3.6.1.tgz | tar -xvz --strip-components 1 -f - && \
    ./configure --prefix=/usr/local && make && sudo -H make altinstall && \
    sudo -H /usr/local/bin/python3.6 -m ensurepip --upgrade && \
    sudo rm -rf /tmp/cpython3.6-build
```

1. If you have pre-existing installation, clean it: `sudo -H /usr/local/bin/python3.6 -mpip uninstall -y pyOpenSSL cryptography requests`
     a. Purges out any pre-existing install to make it clean.
2. Install requests + pyOpenSSL to provoke the issue along with the latest cryptography
```
[ben@ec2-xxx-xxx-xxx-xxx node102 ~]$ sudo -H /usr/local/bin/python3.6 -mpip install pyOpenSSL cryptography requests
Collecting pyOpenSSL
  Using cached pyOpenSSL-17.5.0-py2.py3-none-any.whl
Collecting cryptography
  Using cached cryptography-2.1.4-cp36-cp36m-manylinux1_x86_64.whl
Collecting requests
  Using cached requests-2.18.4-py2.py3-none-any.whl
Requirement already satisfied: six>=1.5.2 in /usr/local/lib/python3.6/site-packages (from pyOpenSSL)
Requirement already satisfied: idna>=2.1 in /usr/local/lib/python3.6/site-packages (from cryptography)
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/local/lib/python3.6/site-packages (from cryptography)
Requirement already satisfied: cffi>=1.7; platform_python_implementation != "PyPy" in /usr/local/lib/python3.6/site-packages (from cryptography)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/site-packages (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography)
Installing collected packages: cryptography, pyOpenSSL, requests
Successfully installed cryptography-2.1.4 pyOpenSSL-17.5.0 requests-2.18.4
```
3. 
```
[ben@ec2-xxx-xxx-xxx-xxx node102 ~]$ /usr/local/bin/python3.6 -c "from urllib3.util.ssl_ import create_urllib3_context
> import requests
> from requests.adapters import HTTPAdapter
>
> CIPHERS = (
>     'DES-CBC3-SHA'
> )
>
>
> class DESAdapter(HTTPAdapter):
>     def init_poolmanager(self, *args, **kwargs):
>         context = create_urllib3_context(ciphers=CIPHERS)
>         kwargs['ssl_context'] = context
>         return super(DESAdapter, self).init_poolmanager(*args, **kwargs)
>     def proxy_manager_for(self, *args, **kwargs):
>         context = create_urllib3_context(ciphers=CIPHERS)
>         kwargs['ssl_context'] = context
>         return super(DESAdapter, self).proxy_manager_for(*args, **kwargs)
>
> s = requests.Session()
> s.mount('https://agences.creditfoncier.fr/', DESAdapter())
> r = s.get('https://agences.creditfoncier.fr/credit-immobilier/toutes-nos-agences')
> print(r.content[:100])
>
> "
Traceback (most recent call last):
  File "<string>", line 21, in <module>
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 126, in __init__
    self.init_poolmanager(pool_connections, pool_maxsize, block=pool_block)
  File "<string>", line 12, in init_poolmanager
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 272, in create_urllib3_context
    context.set_ciphers(ciphers or DEFAULT_CIPHERS)
  File "/usr/local/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 409, in set_ciphers
    self._ctx.set_cipher_list(ciphers)
  File "/usr/local/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1141, in set_cipher_list
    _lib.SSL_CTX_set_cipher_list(self._context, cipher_list) == 1
  File "/usr/local/lib/python3.6/site-packages/OpenSSL/_util.py", line 67, in openssl_assert
    exception_from_error_queue(error)
  File "/usr/local/lib/python3.6/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'SSL_CTX_set_cipher_list', 'no cipher match')]
[ben@ec2-xxx-xxx-xxx-xxx node102 ~]$
```
4. Remove the tainted `cryptography` install
```
[ben@ec2-xxx-xxx-xxx-xxx node102 ~]$ sudo -H /usr/local/bin/python3.6 -m pip uninstall -y cryptography
Uninstalling cryptography-2.1.4:
  Successfully uninstalled cryptography-2.1.4
[ben@ec2-xxx-xxx-xxx-xxx node102 ~]$
```

5. Now insist that we **avoid the binary wheel and build our own cryptography**
```
[ben@ec2-xxx-xxx-xxx-xxx node102 ~]$ sudo -H /usr/local/bin/python3.6 -m pip install --no-binary cryptography cryptography
Collecting cryptography
  Using cached cryptography-2.1.4.tar.gz
Requirement already satisfied: idna>=2.1 in /usr/local/lib/python3.6/site-packages (from cryptography)
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/local/lib/python3.6/site-packages (from cryptography)
Requirement already satisfied: six>=1.4.1 in /usr/local/lib/python3.6/site-packages (from cryptography)
Requirement already satisfied: cffi>=1.7 in /usr/local/lib/python3.6/site-packages (from cryptography)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/site-packages (from cffi>=1.7->cryptography)
Installing collected packages: cryptography
  Running setup.py install for cryptography ... done
Successfully installed cryptography-2.1.4
[ben@ec2-xxx-xxx-xxx-xxx node102 ~]$
```

5. Try the faulted example again:
```
[ben@ec2-xxx-xxx-xxx-xxx node102 ~]$ /usr/local/bin/python3.6 -c "from urllib3.util.ssl_ import create_urllib3_context
> import requests
> from requests.adapters import HTTPAdapter
>
> CIPHERS = (
>     'DES-CBC3-SHA'
> )
>
>
> class DESAdapter(HTTPAdapter):
>     def init_poolmanager(self, *args, **kwargs):
>         context = create_urllib3_context(ciphers=CIPHERS)
>         kwargs['ssl_context'] = context
>         return super(DESAdapter, self).init_poolmanager(*args, **kwargs)
>     def proxy_manager_for(self, *args, **kwargs):
>         context = create_urllib3_context(ciphers=CIPHERS)
>         kwargs['ssl_context'] = context
>         return super(DESAdapter, self).proxy_manager_for(*args, **kwargs)
>
> s = requests.Session()
> s.mount('https://agences.creditfoncier.fr/', DESAdapter())
> r = s.get('https://agences.creditfoncier.fr/credit-immobilier/toutes-nos-agences')
> print(r.content[:100])
>
> "
b'<!DOCTYPE html>\r\n<!--[if IE 6]>\r\n<html class="ie ie6" lang="fr">\r\n<![endif]-->\r\n<!--[if IE 7]>\r\n<htm'
[ben@ec2-xxx-xxx-xxx-xxx node102 ~]$
```

Yeah, it's definitely a problem with the wheels.

Please note that the above vector also fails/works on OSX, if you remove the `sudo -H`, install a homebrew python3.6 and use a virtualenv (you don't want to screw up your system-wide install).

**Comment by alex** [comment] 2018-01-16 23:40
I'm able to reproduce this with the following simplified code:

```py
import socket
import sys

from OpenSSL import SSL


def main():
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    ctx = SSL.Context(SSL.SSLv23_METHOD)
    ctx.set_cipher_list(b"ALL")

    conn = SSL.Connection(ctx, s)
    conn.connect(("www.howsmyssl.com", 443))
    conn.do_handshake()
    conn.sendall(b"GET /a/check HTTP/1.1\r\nHost: www.howsmyssl.com\r\n\r\n")
    while True:
        try:
            data = conn.recv(16384)
        except SSL.ZeroReturnError:
            break
        if not data:
            break
        sys.stdout.write(data)



if __name__ == "__main__":
    main()
```

I believe it'd be possible to add these back by adding some legacy flags to OpenSSL, but I'd prefer we not. The scope of this breakage is very limited, applies exclusively to ciphers with known security concerns, and can be resolved by providing your own OpenSSL.

Opinions @reaperhulk ?

**Comment by benjolitz** [comment] 2018-01-17 05:04
The real problem is that the API design doesn't inform you that the wheels are distributed with zero weak ciphers. It doesn't make it obvious that the SSL library is built with non-standard options.

Finally, it doesn't mean you're insecure by compiling the bad ciphers in, considering:

A) every use case I've seen specifies default high security ciphers
B) you have to opt-in to enable the weak ciphers specially

Another thing to note is the downstream dependencies that are affected include pyOpenSSL and by extension every pyOpenSSL user (scrapy! Requests?). Scrapy, in particular, would need to be able to act more akin to a web browser which necessitates a way to opt-in to weak ciphers.

All tutorials and write ups that allow for use of weak ciphers on a special case basis are broken because there isn't visibility on whether the distributed OpenSSL is silently compiled differently nor is there an easy way to see what is supported by cryptography.

Now, if cryptography:

- makes it clear and obvious that distributed OpenSSL-related assets are missing ciphers
- provides an API to list the supported ciphers like `openssl ciphers` and reasonably catches the case where requested ciphers cannot be provided due to not being built-in

Then I would've been able to reasonably figure out what the problem was.

**Comment by benjolitz** [comment] 2018-01-17 05:09
I'm not against per-se reasonably high security. That's okay. Spending a few days tracking down an upstream dependency of a dependency giving different results despite configuring with standard/default options - not so fun

**Comment by reaperhulk** [comment] 2018-01-17 18:49
Just to clarify, we are distributing OpenSSL 1.1.0 with the default set of ciphers upstream enables. This issue would be present if compiled against the Debian stretch OpenSSL 1.1.0 as well. It affects all of our wheels across macOS, linux, and Windows (all of which use the same default configuration).

The lack of easy introspection here is a problem. We should add a way to get the supported ciphers, but I think that belongs in pyOpenSSL since that's where all the TLS connections will be made. We have `SSL_get_cipher_list` bound so adding a `get_cipher_list` on `SSL` that returns a list of ciphersuite strings would be pretty easy.

Potentially we should also add something to the docs explaining that legacy ciphers are no longer enabled in cryptography's wheels (and a pointer to `--no-binary cryptography` as the blessed workaround), but I'm not sure if that belongs in pyOpenSSL or our docs...

**Comment by reaperhulk** [comment] 2018-01-17 18:53
Having said that it appears https://pyopenssl.org/en/stable/api/ssl.html#OpenSSL.SSL.Connection.get_cipher_list is exactly that API. Is this possibly insufficient?

**Comment by benjolitz** [comment] 2018-01-17 22:44
I would consider it insufficient given that one has to make an Context, pass that into the confusingly named Connection object to get the ciphers, then look for the missing ciphers by comparing against the input cipher string. Of course, OpenSSL makes it terribly obnoxious because if it finds even one cipher match in a list of set_cipher, it silently accepts it. Pegaps our best bet would be to dump the "ALL" cipher family and compare against our desired ciphers?

That's the only way I figured this out -  to call set cipher for the exact missing cipher (or cipher family) and guess that the exception meant it wasn't even compiled in. Eventually I realized that my openssl wasn't being used but someone elses.

Are you sure you're using default configure options for OpenSSL? Perhaps I have an earlier version that has sensible defaults. Need to look into that. 

It reasonable to disable insecure ciphers by default. It does not seem reasonable to completely omit said ciphers from the compiled artifact given that the one must explicitly test for a missing cipher to know its not compilee in. When I add known good ciphers to the cipher list along with the missing ciphers, OpenSSL quietly ignores the missing cipher.

Of all the "fundamental" blocks of our ecosystem, I've always found OpenSSL's decisions to be nearly undebuggable, usually because their API design seems to swallow errors.

What I do know is that there exists at least two very large projects in the Python ecosystem that will fail in a confusing/undebuggable manner for websites running since TLS1.0/SSLv3 days.


I can try asking the random bank websites that I encounter for location list management to upgrade their ancient IIS insallations, but I doubt they'll make any change. Meanwhile, less technical users will discover to their dismay that their scrapy crawlers just won't work for websites because the cryptography OpenSSL bundled object quietly hides the fact that it will never work because the missing ciphers simply never made it into the artifact.

I'm not "blocked", but it is a near certainty that others are blocked by this decision and unaware that the cause of the trouble is a upstream dependency of a dependency.

**Comment by raphaelsamy** [comment] 2018-04-10 20:49
This is such a huge problem thank you very much for breaking it down, now I know why my scrapy and requests projects are breaking..

**Comment by benjolitz** [comment] 2018-04-14 19:16
You're welcome. If you use Scrapy, I've posted a helper function and a way to detect missing ciphers through using Twisted's AcceptableCiphers data structure (https://github.com/scrapy/scrapy/issues/3065#issuecomment-381352245), which internally will follow @reaperhulk 's suggestion of creating the SSL.Connection, setting the cipher list and returning it. In order detect entire missing families of ciphers, one has to test each cipher family at a time and handle the case of an entire missing family.

**Comment by reaperhulk** [comment] 2018-08-29 22:02
The error msg from pyopenssl should be improved (and perhaps pyopenssl's documentation updated to explain how to compile its dependency such that you can access legacy/insecure ciphers), but there's nothing cryptography is going to do here as we want our wheels to represent current security best practice for the vast majority of users. Please open an issue against pyopenssl/submit a PR and it can be handled on that side!

**Closed by reaperhulk** 2018-08-29 22:02 UTC
