### ISSUE TITLE
typo? Certificat versus Certificate in cryptography.hazmat.bindings._rust.x509.Certificat

### ISSUE THREAD

**Issue by milahu** [pyca/cryptography#11045] opened 2024-06-01 08:14 UTC
the string `Certificat` does not appear in the source
so this looks like an "off by one" error

```sh
git clone --depth=1 https://github.com/pyca/cryptography
cd cryptography
grep -r -w Certificat | wc -l
# 0
```

https://github.com/pyca/cryptography/blob/5fbb323a1050b8f37a6348072b1b0c15be6cbd63/src/cryptography/hazmat/bindings/_rust/x509.pyi#L56

with cryptography-42.0.5

<details>
<summary>
test.py
</summary>

```py
#!/usr/bin/env python3

import os
import sys
import time
import subprocess
import tempfile
import random
from multiprocessing import Process
from http.server import HTTPServer, SimpleHTTPRequestHandler
import ssl
import datetime

import cryptography

from cryptography import x509
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.x509.oid import NameOID
from cryptography.hazmat.primitives.serialization import Encoding
from cryptography.hazmat.primitives.serialization import pkcs7
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import serialization

def create_cert(name, issuer_cert=None, issuer_key=None):

    print(f"creating cert {repr(name)}")

    # https://cryptography.io/en/latest/x509/reference/#x-509-certificate-builder
    # https://stackoverflow.com/questions/56285000/python-cryptography-create-a-certificate-signed-by-an-existing-ca-and-export

    key = rsa.generate_private_key(
        public_exponent=65537,
        # key_size=2048 is slow, but python requires 2048 bit RSA keys
        # https://github.com/python/cpython/raw/main/Modules/_ssl.c
        # @SECLEVEL=2: security level 2 with 112 bits minimum security (e.g. 2048 bits RSA key)
        key_size=2048,
        backend=default_backend()
    )

    subject_name = x509.Name([
        x509.NameAttribute(NameOID.COUNTRY_NAME, u"US"),
        x509.NameAttribute(NameOID.STATE_OR_PROVINCE_NAME, u"Texas"),
        x509.NameAttribute(NameOID.LOCALITY_NAME, u"Austin"),
        x509.NameAttribute(NameOID.ORGANIZATION_NAME, u"My Company"),
        x509.NameAttribute(NameOID.COMMON_NAME, name),
    ])

    # root cert: issuer == subject
    issuer_name = issuer_cert.subject if issuer_cert else subject_name

    cert = x509.CertificateBuilder()

    cert = cert.subject_name(subject_name)
    cert = cert.issuer_name(issuer_name)
    cert = cert.public_key(key.public_key())
    cert = cert.serial_number(x509.random_serial_number())
    cert = cert.not_valid_before(datetime.datetime.utcnow())
    cert = cert.not_valid_after(datetime.datetime.utcnow() + datetime.timedelta(days=3650))

    if not issuer_cert:
        cert = cert.add_extension(x509.BasicConstraints(ca=True, path_length=None), critical=True)

    cert = cert.sign(key, hashes.SHA256(), default_backend())

    return cert, key

cert, key = create_cert("asdf")
# raise some error
print(cert.get_subject())
```

</details>

```
creating cert 'asdf'
Traceback (most recent call last):
  File "test.py", line 70, in <module>
    print(cert.get_subject())
          ^^^^^^^^^^^^^^^^
AttributeError: 'cryptography.hazmat.bindings._rust.x509.Certificat' object has no attribute 'get_subject'
```

also mentioned in #10962

> Note 'Certificat' instead of 'Certificate'

**Comment by reaperhulk** [comment] 2024-06-01 11:02
I can't reproduce this in `main`. It was likely fixed in a pyo3 release that we haven't shipped in a released version yet.

**Comment by alex** [comment] 2024-06-01 13:03
This isn't a pyo3 issue, it's a Python limitation in certain versions. I fixed it in https://github.com/python/cpython/commit/543009347e7cfcc495ca8553fab8d622dcfd18e3

**Closed by alex** 2024-06-01 13:03 UTC
