### ISSUE TITLE
Wrong link OPENSSL_VERSION & SSL.SSLEAY_VERSION

### ISSUE THREAD

**Issue by airdissy** [pyca/cryptography#3057] opened 2016-07-23 14:34 UTC
Hello everyone, 

I'm quite a rookie for this kind of matter.
I upgraded my openssl after installing first cryptography. 
Now I get 

```
File "/Library/Python/2.7/site-packages/cryptography-1.4-py2.7-macosx-10.10-intel.egg/cryptography/hazmat/bindings/openssl/binding.py", line 230, in _verify_openssl_version
    "You are linking against OpenSSL 0.9.8, which is no longer "
RuntimeError: You are linking against OpenSSL 0.9.8, which is no longer support by the OpenSSL project. You need to upgrade to a newer version of OpenSSL.
```

However my openssl is updated

`python -c "import ssl; print ssl.OPENSSL_VERSION" OpenSSL 1.0.2h  3 May 2016`

but not here 
`python -c 'import OpenSSL.SSL as SSL; print SSL.SSLeay_version(SSL.SSLEAY_VERSION)'
OpenSSL 0.9.8zc 15 Oct 2014`

I did'nt find how to link both cryptography and my last version of open ssl.
I tried to uninstall cryptograpy with pip but didn't work until the end since a lack of right to delete files. I try to upgrade everything but already last version for all packages.

So any help would be very cool !
Peter

**Comment by airdissy** [comment] 2016-07-23 14:42
Sorry I just see same issues there with answer but I'm not sure how to do it, so I asked question in that topic.
 https://github.com/pyca/cryptography/issues/3043

Thanks,
Peter

**Comment by alex** [comment] 2016-07-23 14:44
Closing as a duplicate of that issue.

**Closed by alex** 2016-07-23 14:44 UTC
