### ISSUE TITLE
cryptography wheel for Windows arm64

### ISSUE THREAD

**Issue by saschanaz** [pyca/cryptography#11468] opened 2024-08-21 21:36 UTC
This would like require a windows arm64 runner, which is not available yet: https://github.blog/news-insights/product-news/arm64-on-github-actions-powering-faster-more-efficient-build-systems/

I'm filing this just to track for now.

**Comment by alex** [comment] 2024-08-21 21:49
Closing as a dupe of https://github.com/pyca/cryptography/issues/11199. Please search for existing issues before filing new ones.

**Closed by alex** 2024-08-21 21:49 UTC
