### ISSUE TITLE
Investigate adding a PBKDF2 recipe

### ISSUE THREAD

**Issue by Ayrx** [pyca/cryptography#1149] opened 2014-06-19 00:30 UTC
I think it might be a good idea to have a PBKDF2 password hashing recipe that takes care of things like salt generation, encoding etc. Perhaps something interoperable with passlib's implementation?

**Comment by wkral** [comment] 2015-02-06 18:24
It would be useful to have this recipe, while passlib itself supports Python 3 for native implementations it relies on M2Crypto which doesn't. As @dlitz  pointed out by using a pure python implementation with a smaller work factor you give attackers a large advantage if they ever get access to your database.

Having a recipe for password storage with good defaults for developers not using Django and using Python 3 with a native implementation would be useful especially for people who don't know about OWASP and doing the research to find out about PBKDF2 or scrypt.

python-pkbdf2 and pycrypto work with Python 3 but I'd wager a lot of devs don't necessarily know to even look up pbkdf2. Having a recipe that generates safe password hashes and can verify them with constant time might save a lot of people from making a lot of mistakes.

**Comment by reaperhulk** [comment] 2015-02-06 18:42
@wkral it sounds like a good first approach would be proposing a PR to switch passlib away from m2crypto?

**Comment by reaperhulk** [comment] 2015-02-06 18:49
I'm reluctant to build general purpose recipes for password hashing without a spec others can implement (e.g. How the dynamic iterations are determined, algorithm used, what format we serialize the metadata into, how you handle password migrations, etc). If such a spec already exists I'm interested in an implementation though.

**Comment by alex** [comment] 2015-02-06 19:35
Maybe it's worth turning what django does into an external spec?

**Comment by dstufft** [comment] 2015-02-06 20:12
I'm pretty much -1 on cryptography getting a general password hashing system at the higher level. We should direct people to passlib. If the passlib backends aren't good enough we should contribute a backend to them. The problem is just implementing a password hasher isn't the whole story because you need an API to handle upgrades and downgrades between various algorithms.

I think we shouldn't try to compete with passlib unless someone can demonstrate one of:

* A better API for password hashing than the high level API that passlib provides that still takes into account the need to upgrade/downgrade password hashes as time goes on.
* A reason why the passlib codebase is demonstrably dangerous.

and has a good reason for why those things cannot be implemented/fixed inside inside of passlib itself or why that is not a workable solution to the problem.

I do however thing that passlib should support using cryptography itself as a backend for it's password hashing and I think that patches etc should be made over there to make that happen.

**Comment by alex** [comment] 2015-02-06 21:17
+1 from me -- maybe we should collectively review passlib to see that it
meats our standards for a recipe and then add a thing about that ot the FAQ?

On Fri, Feb 6, 2015 at 12:12 PM, Donald Stufft <notifications@github.com>
wrote:

> I'm pretty much -1 on cryptography getting a general password hashing
> system at the higher level. We should direct people to passlib. If the
> passlib backends aren't good enough we should contribute a backend to them.
> The problem is just implementing a password hasher isn't the whole story
> because you need an API to handle upgrades and downgrades between various
> algorithms.
>
> I think we shouldn't try to compete with passlib unless someone can
> demonstrate one of:
>
>    - A better API for password hashing than the high level API that
>    passlib provides that still takes into account the need to
>    upgrade/downgrade password hashes as time goes on.
>    - A reason why the passlib codebase is demonstrably dangerous.
>
> and has a good reason for why those things cannot be implemented/fixed
> inside inside of passlib itself or why that is not a workable solution to
> the problem.
>
> I do however thing that passlib should support using cryptography itself
> as a backend for it's password hashing and I think that patches etc should
> be made over there to make that happen.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/issues/1149#issuecomment-73304361>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by Ayrx** [comment] 2015-02-07 02:23
@dstufft I don't think passlib actually handles the part about "API to handle upgrades and downgrades between various algorithms" unless I'm missing a key part of the library. I always roll my own to handle that aspect.

Anyway, my two quibbles with passlib is that it supports way too many obscure algorithms (can't fault passlib for this really) and that the code has too many levels of indirection. Nothing bad from a security POV though.

**Comment by dstufft** [comment] 2015-02-07 02:34
@Ayrx From: [passlib's documentation on Deprecation & Hash Migration](https://pythonhosted.org/passlib/lib/passlib.context-tutorial.html#deprecation-hash-migration)

```python
from passlib.context import CryptContext

from myapp import (
    get_hash_from_user, replace_user_hash, do_successful_things,
    reject_user_login,
)

ctx = CryptContext(
    schemes=["sha256_crypt", "md5_crypt", "des_crypt"],
    deprecated=["md5_crypt", "des_crypt"],
)

pwhash = get_hash_from_user(user)
valid, new_hash = pass_ctx.verify_and_update(password, pwhash)
if valid:
    if new_hash:
        replace_user_hash(user, new_hash)
    do_successful_things()
else:
    reject_user_login()
```

They also have separate APIs for verifying the hash, checking if it needs an update, and of course hashing a plaintext password. I can't personally think of a much better API then that though without having to delve into things like "where are my passwords stored" and such.

The upgrade API will manage upgrading between different algorithms as well as handling upgrading within a single algorithm but with different configurations. It's fairly configurable, for instance you can specify a range of acceptable values for rounds instead of just a set value so you can slowly migrate people over time without having each bump of the number of rounds causing every user to need to re-hash.

I actually think that supporting obscure algorithms is a **good** thing, because it means it's more likely that you can take passlib with some particular existing database of users and drop it in there and have it available to authenticate your existing users and then you get the upgrade API and new hashing overtime.

**Comment by Ayrx** [comment] 2015-02-07 02:39
Huh, that's handy. I wished I had known about it earlier. +1 then on taking a look at recommending passlib in our docs.

**Comment by wkral** [comment] 2015-02-13 17:34
If passlib is going to be the recommended library, then some work needs to be done to update it to Python 3 with native performance primitives. I seriously considered it but couldn't use it for that reason. The project hasn't been updated for more than a year as well which factored into my consideration.

If cryptography can become the backer for that project that satisfies my needs and would hopefully save some other developers from saving passwords poorly. Hopefully these projects can collaborate.

**Comment by alex** [comment] 2016-03-06 15:05
Closing this since the desirable recipe is really password storage (e.g. for web authentication) and there's already adequest external solutions.

**Closed by alex** 2016-03-06 15:05 UTC
Labels: api design, recipes
