### ISSUE TITLE
Host Check, Sig Check; CA Flag Check; Date Check?

### ISSUE THREAD

**Issue by egberts** [pyca/cryptography#5494] opened 2020-10-23 20:18 UTC
In ~2016, Yasmin Acar wrote this **_Comparing the Usability of Cryptographic APIs_** [link](https://www.cl.cam.ac.uk/~rja14/shb17/fahl.pdf) white paper which detailed a massive comparison between various crypto libraries.

And I noticed that cryptography.io library managed to shine the most ... in a good way.

However, I noticed in Appendix B, that it failed the 4 basic check of certificates and PEM files.

I was wondering if that has been addressed yet.

I've searched by author, article title, and this issue title and found no corresponding issue.

**Comment by alex** [comment] 2020-10-23 20:22
This is effectively a duplicate of #2381. We currently have no APIs for doing any x.509 chain building or similar.

**Closed by alex** 2020-10-23 20:22 UTC
