### ISSUE TITLE
TypeError: 'type' object is not iterable  in   "cryptography/x509/name.py", line 28

### ISSUE THREAD

**Issue by relunctance** [pyca/cryptography#4020] opened 2017-11-15 09:59 UTC
"cryptography/x509/name.py", line 28, in <module>
    _ASN1_TYPE_TO_ENUM = dict((i.value, i) for i in _ASN1Type)
TypeError: 'type' object is not iterable

**Comment by relunctance** [comment] 2017-11-15 10:07
pip uninstall enum
pip install enum34

can fixed this bug

**Comment by reaperhulk** [comment] 2017-11-15 10:47
We list `enum34` in our requirements already. It might make sense to add this to the FAQ though.

**Comment by alex** [comment] 2017-11-20 22:29
Dupe of #4010

**Closed by alex** 2017-11-20 22:29 UTC

**Comment by tannupiyush** [comment] 2018-11-23 09:08
i am getting same error!!  i am unable to unintsall enum and install enum34..
pip uninstall enum
pip install enum34
By using these commands i am unable fix bug.can i can any solution or reason for this issue?

**Comment by tongpinmo** [comment] 2019-01-18 00:33
@harshini4 @tannupiyush have you ever solved the problem ,running pip uninstall enum gives me the same TypeError.

**Comment by nithinn86** [comment] 2019-01-30 23:57
@tongpinmo , I had the same issue, was able to solve it by manually removing enum and crapytography. Here are the steps that I did - 
1. Removed enum from "/usr/lib/python2.7/dist-packages": rm -rf enum*
2. When I tried to install enum34 using "pip install enum34" I still run into the same error from cryptography: "TypeError: 'type' object is not iterable". (I think its because there is a copy of enum present under "/usr/local/lib/python2.7/dist-packages" as well.
3. Next I removed cryptography from "/usr/lib/python2.7/dist-packages": rm -rf cryptography*
4. Now try running "pip uninstall enum", it works.
5. Then install enum34: pip install enum34
6. Then install cryptography again: pip install cryptography

**Comment by tongpinmo** [comment] 2019-01-31 02:21
> 2\. s

ok,thank you very much

**Comment by tongpinmo** [comment] 2019-01-31 02:21
@nithinn86 ok,thank you very much

**Comment by autodataming** [comment] 2019-04-23 01:54
pipenv install enum34

**Comment by jpmelos** [comment] 2019-10-14 21:21
None of the methods provided here worked for me. I can't uninstall `enum` because my venv says it's not installed, and installing `enum34` manually doesn't take care of it no matter how many times I reinstall `cryptography`. Maybe we need a real solution for this problem. It seems like not using `enum` is such an easy thing to do?
