### ISSUE TITLE
TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by gigkokman** [pyca/cryptography#3026] opened 2016-06-30 05:06 UTC
I was running nosetests with sniffer (auto-run nosetests), first running is ok, but got NoneType error so on.

**My packages:**
```
cffi==1.7.0
cryptography==1.4
MacFSEvents==0.7
MarkupSafe==0.23
mock==2.0.0
MySQL-python==1.2.5
nose==1.3.7
pyOpenSSL==16.0.0
sniffer==0.3.5
```

**Error message:**

```
TypeError: 'NoneType' object has no attribute '__getitem__'
From cffi callback <bound method type._lock_cb of <class 'cryptography.hazmat.bindings.openssl.binding.Binding'>>:
Traceback (most recent call last):
  File "venv/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 205, in _lock_cb
    lock = cls._locks[n]
```

**Comment by alex** [comment] 2016-07-02 00:04
Are you able to share a program with which we can reproduce this?

**Comment by gigkokman** [comment] 2016-07-04 09:35
Sorry @alex,
error had completely disappeared when I removed virtualenv create new one.
So, Should I close this issue?

**Comment by alex** [comment] 2016-07-04 12:32
If you're unable to reproduce, then yes, we'll close this.

**Closed by alex** 2016-07-04 12:32 UTC
