### ISSUE TITLE
PKCS1 OAEP  encryption with SHA256 hashing 

### ISSUE THREAD

**Issue by astrodsg** [pyca/cryptography#2340] opened 2015-09-14 22:42 UTC
I'm trying to run the following code:

    from cryptography.hazmat.backends import default_backend
    from cryptography.hazmat.primitives.asymmetric import rsa, padding
    
    key_size = 256*8
    private_key = rsa.generate_private_key(
        public_exponent=65537,
        key_size=key_size,
        backend=default_backend()
    )
    message = b'secret'
    encrypted = private_key.public_key().encrypt(
        message,
        padding.OAEP(
            mgf=padding.MGF1(algorithm=hashes.SHA256()),
            algorithm=hashes.SHA256(),
            label=None,
    )

However I get an error ```cryptography.exceptions.UnsupportedAlgorithm: This backend supports only SHA1 inside MGF1 when using OAEP.``` 

Is there a good reason why SHA256 is not supported? or has it simply just not been implemented?

**Comment by reaperhulk** [comment] 2015-09-14 22:43
SHA256 signatures themselves are supported, it's using SHA256 inside the mask generation function that is not. OpenSSL 1.0.2 *does* support that, but it's an extremely unusual configuration. This is typically how "SHA256" OAEP is accomplished:

```
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.asymmetric import rsa, padding

key_size = 256*8
private_key = rsa.generate_private_key(
    public_exponent=65537,
    key_size=key_size,
    backend=default_backend()
)
message = b'secret'
encrypted = private_key.public_key().encrypt(
    message,
    padding.OAEP(
        mgf=padding.MGF1(algorithm=hashes.SHA1()),
        algorithm=hashes.SHA256(),
        label=None,
)
```

**Comment by astrodsg** [comment] 2015-09-14 22:47
That raises the same error. In cryptography.hazmat.backends.openssl.rsa there are two if statements, one at L52 the other L62 which restrict only SHA1 for both the mask generation and signature.

**Comment by reaperhulk** [comment] 2015-09-14 22:50
Ah, you're quite correct. It's been too long since we wrote that section. Looks like we need to expand support there. It's possible we originally restricted it because of limitations in the OpenSSL backend, but I don't recall offhand.

**Comment by astrodsg** [comment] 2015-09-14 22:57
Could be. I was getting a similar hash function restriction when trying to sign json web tokens using PyJWT and an  'PS256'  algorithm (```jwt.encode({'hello': 'world'}, key, 'PS256')```)

```UnsupportedAlgorithm: When OpenSSL is older than 1.0.1 then only SHA1 is supported with MGF1.```

**Comment by astrodsg** [comment] 2015-09-14 22:58
The version of openssl I have installed is 1.0.2.d but I think cryptography depends on it's own binary .so files.

**Comment by reaperhulk** [comment] 2015-09-14 23:09
It depends what platform you're on. We ship static wheels on Windows (and in certain cases for OS X now), but otherwise we dynamically link against OpenSSL as found in the libpath. On OS X < 10.11 that will link against 0.9.8 unless you supply appropriate LDFLAGS and CFLAGS to point it at homebrew or macports. You can see what you're linked against with `python -c "from cryptography.hazmat.backends.openssl.backend import backend;print(backend.openssl_version_text())"`. (The SHA256 OAEP limit is currently enforced at the Python layer though so it won't work no matter what version of OpenSSL you're linked against)

**Comment by reaperhulk** [comment] 2015-09-29 13:38
Adding support for this is largely blocked on finding non-SHA1 OAEP test vectors (both SHA1 and non-SHA1 MGF1 as well).

**Comment by alex** [comment] 2016-03-05 15:50
So there's only one tracking bug here, I'm going to close this as a dupe of #2340

**Comment by alex** [comment] 2016-03-05 15:50
Sorry, as a dupe of #1663

**Closed by alex** 2016-03-05 15:50 UTC
Labels: backend, primitives
