### ISSUE TITLE
Loading OpenSSL backend is excruciatingly slow

### ISSUE THREAD

**Issue by sailorfred** [pyca/cryptography#1764] opened 2015-03-19 21:54 UTC
(v_env)vagrant@vagrant-ubuntu-trusty-64:/a8src/gcmcrypt$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import time
>>> now=time.time(); from cryptography.hazmat.backends.openssl import backend; duration=time.time() - now
>>> duration
1.9470350742340088
>>> 

dstuft on IRC indicates that the time is being spent in cffi parsing of headers.

**Comment by reaperhulk** [comment] 2015-03-20 16:06
@sailorfred unfortunately this is an issue with the way cffi is currently architected. I'd suggest filing this as an upstream issue (https://bitbucket.org/cffi/cffi) to start a discussion about how this could be improved.

**Comment by sailorfred** [comment] 2015-03-24 18:54
Shot in the dark: does https://bitbucket.org/cffi/cffi/issue/66/many-calls-to-cdef-is-much-much-slower have any relevance?

**Comment by sailorfred** [comment] 2015-03-24 19:06
https://bitbucket.org/cffi/cffi/issue/188/excrucatingly-slow-when-importing-openssl

**Comment by alex** [comment] 2015-05-26 23:43
Closing this as a dupe of #1982, which is measured to dramatically improve this.

**Closed by alex** 2015-05-26 23:43 UTC
