### ISSUE TITLE
pyinstaller 'cryptography/hazmat/primitives/src/padding.h' problem

### ISSUE THREAD

**Issue by recotak** [pyca/cryptography#1860] opened 2015-04-22 15:39 UTC
Hi,

i had written some testcode with cryptography library. While trying to pack it with pyinstaller it ends with the same problem:
```
IOError: [Errno 2] No such file or directory: '/tmp/_MEINY96uU/cryptography/hazmat/primitives/src/padding.h'
```
The testcode:
```
from cryptography.fernet import Fernet
key = "vYfdEiaA17supEzBLL6MY-t0zumDcGMGPVOQTv3D_lo="
f = Fernet(key)
```

```
pyinstaller -F test_fernet.py
```

Any idea?

**Comment by alex** [comment] 2015-04-23 00:45
I'm not really sure what to suggest here, @dstufft do we know anything about pyinstaller?

**Comment by dstufft** [comment] 2015-04-23 00:49
The problem is going to be the fact that pyinstaller puts the python files inside of a zip file but the data files inside of a temporary directory. If we're going to support pyinstaller we'd want to do something like:

```python
import sys
import os

if getattr(sys, 'frozen', False):
    # we are running in a |PyInstaller| bundle
    basedir = sys._MEIPASS
else:
    # we are running in a normal Python environment
    basedir = os.path.dirname(__file__)
```

To determine the base directory to load the ``.h`` and ``.c`` files from.

**Comment by alex** [comment] 2015-04-23 00:52
Uhhh. That sounds like a bad approach, IMO we shouldn't need ot write any
pyinstaller specific code. If we use the <apis whose name I forget that you
use to make something zip_safe, where you don't use open() to get a file>
does that fix it?

On Wed, Apr 22, 2015 at 8:49 PM, Donald Stufft <notifications@github.com>
wrote:

> The problem is going to be the fact that pyinstaller puts the python files
> inside of a zip file but the data files inside of a temporary directory. If
> we're going to support pyinstaller we'd want to do something like:
>
> import sysimport os
> if getattr(sys, 'frozen', False):
>     # we are running in a |PyInstaller| bundle
>     basedir = sys._MEIPASSelse:
>     # we are running in a normal Python environment
>     basedir = os.path.dirname(__file__)
>
> To determine the base directory to load the .h and .c files from.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/issues/1860#issuecomment-95377453>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by dstufft** [comment] 2015-04-23 00:53
No idea, I don't know PyInstaller that well, I only know because I saw that snippet of code in their documentation.

**Comment by alex** [comment] 2015-04-23 00:53
I'm willing to do the <stadnard API for data files>, PyInstaller specific
stuff I'd be opposed to.

On Wed, Apr 22, 2015 at 8:53 PM, Donald Stufft <notifications@github.com>
wrote:

> No idea, I don't know PyInstaller that well, I only know because I saw
> that snippet of code in their documentation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/issues/1860#issuecomment-95377847>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by dstufft** [comment] 2015-04-23 00:53
Though I think the answer is "it depends on how the PyInstaller spec was written".

**Comment by reaperhulk** [comment] 2015-06-08 04:34
#1986 may affect this.

**Comment by reaperhulk** [comment] 2015-06-18 03:06
closing in favor of central tracking issue #2039

**Closed by reaperhulk** 2015-06-18 03:06 UTC
Labels: installation
