### ISSUE TITLE
Cryptography build under OpenBSD - SSL-related compilation issue

### ISSUE THREAD

**Issue by belzebubek** [pyca/cryptography#6253] opened 2021-08-31 09:09 UTC
Hi,

In order to compile cryptography under OpenBSD I had to apply below patch (comment out SSL_OP_NO_DTLSv1/SSL_OP_NO_DTLSv1_2), otherwise it throws syntax/definition error.
Not sure how it should be fixed in long run.

$ diff -u /usr/include/openssl/ssl.h.orig /usr/include/openssl/ssl.h
--- /usr/include/openssl/ssl.h.orig     Mon Apr 19 18:16:24 2021
+++ /usr/include/openssl/ssl.h  Tue Aug 31 11:04:10 2021
@@ -521,8 +521,10 @@
 #define SSL_OP_NO_TLSv1_3                              0x20000000L
 #endif

+/*
 #define SSL_OP_NO_DTLSv1                               0x40000000L
 #define SSL_OP_NO_DTLSv1_2                             0x80000000L
+*/

 /* SSL_OP_ALL: various bug workarounds that should be rather harmless. */
 #define SSL_OP_ALL \

**Comment by reaperhulk** [comment] 2021-08-31 14:10
What version of libressl does your system have installed?

**Comment by belzebubek** [comment] 2021-09-10 17:44
# openssl version
LibreSSL 3.3.2

**Comment by reaperhulk** [comment] 2021-09-12 05:29
`cryptography` only defines those values if it thinks LibreSSL is < 3.3.2:

```
#if CRYPTOGRAPHY_LIBRESSL_LESS_THAN_332                                                       
static const long SSL_OP_NO_DTLSv1 = 0;                                                       
static const long SSL_OP_NO_DTLSv1_2 = 0;                                                     
#endif                                                                                        
```

What value do you have for `LIBRESSL_VERSION_NUMBER`? We define our constant like this:

```
#define CRYPTOGRAPHY_LIBRESSL_LESS_THAN_332 \                                                 
    (LIBRESSL_VERSION_NUMBER < 0x3030200f)                                                    
```

**Comment by belzebubek** [comment] 2021-09-14 19:45
/usr/include/openssl/opensslv.h:#define LIBRESSL_VERSION_NUMBER 0x3030200fL

**Comment by reaperhulk** [comment] 2021-09-14 19:59
Okay, looks like we need a reproducer here then. If you boot up a fresh OpenBSD VM do you see this behavior still?

**Comment by belzebubek** [comment] 2021-09-14 20:24
I'm using virtualenv - yes the behavior is the same in new venv.

```
# virtualenv TEST
Using base prefix '/usr/local'
New python executable in /root/TEST/bin/python3.8
Also creating executable in /root/TEST/bin/python
Installing setuptools, pip, wheel...done.
# rm -r /root/.cache/pip/
# . /root/TEST/bin/activate
(TEST) # pip install mailman-web
[...]
Building wheel for cryptography (PEP 517) ... error
[...]
      Finished release [optimized] target(s) in 51.67s
      Finished release [optimized] target(s) in 51.67s
  building '_openssl' extension
  creating build/temp.openbsd-6.9-amd64-3.8/build
  creating build/temp.openbsd-6.9-amd64-3.8/build/temp.openbsd-6.9-amd64-3.8
  cc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -pipe -g -fPIC -O2 -pipe -g -O2 -pipe -g -fPIC -I/usr/local/include/python3.8 -c build/temp.openbsd-6.9-amd64-3.8/_openssl.c -o build/temp.openbsd-6.9-amd64-3.8/build/temp.openbsd-6.9-
amd64-3.8/_openssl.o -Wconversion -Wno-error=sign-conversion
  build/temp.openbsd-6.9-amd64-3.8/_openssl.c:2172:19: error: expected identifier or '('
  static const long SSL_OP_NO_DTLSv1 = 0;
                    ^
  /usr/include/openssl/ssl.h:524:29: note: expanded from macro 'SSL_OP_NO_DTLSv1'
  #define SSL_OP_NO_DTLSv1                                0x40000000L
                                                          ^
  build/temp.openbsd-6.9-amd64-3.8/_openssl.c:2173:19: error: expected identifier or '('
  static const long SSL_OP_NO_DTLSv1_2 = 0;
                    ^
  /usr/include/openssl/ssl.h:525:31: note: expanded from macro 'SSL_OP_NO_DTLSv1_2'
  #define SSL_OP_NO_DTLSv1_2                              0x80000000L
                                                          ^
```

**Comment by reaperhulk** [comment] 2021-09-14 20:32
I need to know if you can reproduce in a fully new VM because the most likely scenario here is that you have multiple copies of OpenSSL/LibreSSL with differing headers in your include search paths. A fresh VM would rule this out, while a virtualenv provides no isolation against the C build environment of the system.

**Comment by belzebubek** [comment] 2021-09-14 20:45
Im using OpenBSD on a dedicated server, not a VM. I do not have any other OpenSSL/LibreSSL versions installed there.
I can confirm the same error is appearing on my other OpenBSD boxes. I can arrange fresh OpenBSD deployed somewhere and grant you access - if you want to.

**Comment by reaperhulk** [comment] 2021-09-14 22:03
Yeah if I could get access to a fresh system to test this that'd be great.

**Comment by belzebubek** [comment] 2021-09-15 08:29
Pls send me your ssh public key to aleksanderde at protonmail dot com. I'll reply to you with access details.

**Comment by reaperhulk** [comment] 2021-09-16 20:59
Turns out this was fixed in https://github.com/pyca/cryptography/pull/5988 and just isn't in 3.4.x. It will be in 35.0 when we release it soon.

**Closed by reaperhulk** 2021-09-16 20:59 UTC
