### ISSUE TITLE
Support for PyInstaller, py2exe, Cx_Freeze and similar tools.

### ISSUE THREAD

**Issue by Ayrx** [pyca/cryptography#2039] opened 2015-06-18 03:05 UTC
Getting cryptography to work with exe freezing tools like PyInstaller, py2exe and Cx_Freeze has been an increasingly popular source of issues. 

Some prior issues includes
- #1524 
- #1860 

The recent work on `master` that ports cryptography to CFFI 1.0 has fixed most of the issues present. The only issue remaining is that our current implementation of detecting available backends with `pkg_resources.iter_entry_points` does not work with such packaging tools (probably due to some sys.path issues).

Patching the `_available_backends()` to use a list of hardcoded backends instead of `pkg_resources.iter_entry_points` allows for successful freezing of apps using cryptography.

I'm opening this issue to track the final hurdle to getting cryptography to work with similar freezing tools.

**Comment by aanand** [comment] 2015-06-18 17:27
As someone who's eagerly awaiting this fix so I can use pyOpenSSL in [Docker Compose](https://github.com/docker/compose), while I'm too ignorant of Python module loading particularities to help out with code, I'm more than happy to test any code changes out with PyInstaller and a non-trivial project.

**Comment by reaperhulk** [comment] 2015-06-21 05:27
https://github.com/pyinstaller/pyinstaller/issues/1188

**Comment by exvito** [comment] 2015-06-25 23:49
Hi all,

First of all, thanks for sharing this great project.

Like @aanand, I'm also interested and available to test progress on this. Meanwhile, I successfully tested an ugly-hack with the latest master (commit 77c98e3c4ef69d0cfee665cd0835670f4ac44242) and pyinstaller 2.1 on a Mac (no resources to try Linux/Windows, now).

Inspired in the original comment by @Ayrx, I created a very simple module/function that monkey patches cryptography.hazmat.backends._available_backends_list: with this and with some manual copying of _cffi_backend.so to the resulting dist/ dir (may need a pyinstaller hook to handle that), I obtained a running executable from the "sample Fernet code" at https://cryptography.io/en/latest/fernet/

I'll leave it here in case it is useful so someone as a stop-gap solution. Just call it before any other cryptography related code.

```python
def patch_crypto_be_discovery():

    """
    Monkey patches cryptography's backend detection.
    Objective: support pyinstaller freezing.
    """

    from cryptography.hazmat import backends

    try:
        from cryptography.hazmat.backends.commoncrypto.backend import backend as be_cc
    except ImportError:
        be_cc = None

    try:
        from cryptography.hazmat.backends.openssl.backend import backend as be_ossl
    except ImportError:
        be_ossl = None

    backends._available_backends_list = [
        be for be in (be_cc, be_ossl) if be is not None
    ]
```
PS: Feeling like trying this on a larger-scale codebase. Not sure I'll have the time soon, though.

**Comment by aem** [comment] 2015-06-26 13:30
To add to the list of cases, I'm currently working on an installer for my company's product, using pyopenssl and cryptography to verify SSL certificates. py2exe compilation fails because cryptography/hazmat/bindings/openssl/src/osrandom_engine.[c,h] don't get pulled in with the rest of the library. Beyond incompatibilities with our build path, for a Python library to be using C source files seems counterintuitive.

**Comment by Ayrx** [comment] 2015-06-26 15:17
@aem That particular issue has been fixed on `master` and will be in the 1.0 release.

**Comment by aem** [comment] 2015-06-26 15:18
@Ayrx ah, sorry. New to the discussion. Is there a projected timeframe for the 1.0 release?

**Comment by Ayrx** [comment] 2015-06-26 15:21
@aem @reaperhulk is the guy to ask for a more specific timeframe but I feel confident in saying "before July". :)

The 1.0 release probably will not solve the remaining issue though, so unless you are willing to use the monkeypatch @exvito suggested py2exe still will not work.

**Comment by reaperhulk** [comment] 2015-06-26 23:56
Before July is probably ambitious at this point due to things like #2061, but within the next 2 weeks is a goal.

**Comment by LEDfan** [comment] 2015-07-04 19:46
I know it's a bit Off topic but for everyone who comes here via a search engine and tries to create an exe of a scrapy spider. Try to remove every connection with the `openssl` library. I did a search in the files (e.g. grep/IDE) and removed the logic itself but let the classes (and the extending of classes) intact. Note that this make it's impossible to spider HTTPS sites.

**Comment by thenewguy** [comment] 2015-07-09 15:59
Current master is working for me with pyinstaller develop branch using either --onedir or --onefile mode without any modifications.  Using pyinstaller commit efd24aaba321738bc2ee0af031f31f24801ecd0f and cryptography commit 907cc81149e6a89db683c206f8fe4fc5bea7f87d building Win32

**Comment by ilvalle** [comment] 2015-07-15 13:43
@thenewguy I've tried dev version of pyinstaller.
I'm getting ```sha1 is not a supported hash on this backend.```
I'm using signxml to verify an xml signed file.
Beside ```import signxml``` should I've to mention particular imports in my code regarding cryptography?

**Comment by aanand** [comment] 2015-07-15 13:48
I can also confirm that the current master is working for me. If it helps at all, I'd be happy to attempt a `git bisect` to find the exact commit that fixed it.

What's the timeline now looking like for this being fixed in a stable release?

**Comment by alex** [comment] 2015-07-15 14:08
As soon as the last issue in "Tenth Release" milestone is finished we'll do
a release. Hopefully in the next couple of days.

Alex

On Wed, Jul 15, 2015 at 9:48 AM, Aanand Prasad <notifications@github.com>
wrote:

> I can also confirm that the current master is working for me. If it helps
> at all, I'd be happy to attempt a git bisect to find the exact commit
> that fixed it.
>
> What's the timeline now looking like for this being fixed in a stable
> release?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/issues/2039#issuecomment-121621971>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by LEDfan** [comment] 2015-07-15 15:09
I downloaded master branch and installed using pip (`pip install x.zip`) and compiled my exe using `py2exe`. I can confirm this is working. Thanks!

**Comment by Ayrx** [comment] 2015-07-17 12:42
@LEDfan Can you share how you got py2exe working?

**Comment by novocaine** [comment] 2015-07-27 16:25
I was able to get this working by patching trunk cryptography in a similar manner to @exvito and then explicitly listing cffi as a package to py2exe, which seemed to not pick it up otherwise.

**Comment by aanand** [comment] 2015-08-14 12:44
Update: using cryptography 1.0, I'm now getting a different error when trying to run the binary built with PyInstaller. Minimal failing case:

```bash
#!/bin/bash

set -ex

# Clean up
rm -rf bin build dist venv || true

# Prepare virtualenv
virtualenv venv
venv/bin/pip install \
  cryptography==1.0 \
  git+https://github.com/pyinstaller/pyinstaller.git@9d0e0ad4c1c02964bbff86edbf7400cd40958b1a#egg=pyinstaller
source venv/bin/activate

# Write the script
mkdir bin
cat > bin/main <<EOF
#!/usr/bin/env python
from cryptography.hazmat.bindings.openssl.binding import Binding
print "Imported Binding"
EOF
chmod +x bin/main

# Test the script
bin/main

# Build the binary
pyinstaller -F bin/main

# Run the binary
dist/main
```

```
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/Users/aanand/work/docker/cryptography-openssl/venv/lib/python2.7/site-packages/PyInstaller/loader/pyi_importers.py", line 271, in load_module
    exec(bytecode, module.__dict__)
  File "/Users/aanand/work/docker/cryptography-openssl/build/main/out00-PYZ.pyz/cryptography.hazmat.bindings.openssl.binding", line 11, in <module>
  File "/Users/aanand/work/docker/cryptography-openssl/venv/lib/python2.7/site-packages/PyInstaller/loader/pyi_importers.py", line 416, in load_module
    module = imp.load_module(fullname, fp, filename, self._c_ext_tuple)
ImportError: No module named _cffi_backend
```

**Comment by mrjefftang** [comment] 2015-08-18 14:16
Cryptography 1.0 packages successfully with cx_Freeze with 2 caveats.

1. Must explicitly package `cffi` as shown below
2. Must explicitly pick a backend instead of `default_backend`, e.g. 
`from cryptography.hazmat.backends import openssl as openssl_backend` instead of `from cryptography.hazmat.backends import default_backend`.

```python
from cx_Freeze import setup

setup(
    ...
    options={
        'packages': ['cffi', 'cryptography'],
    }
    ...
)
```

**Comment by kuba** [comment] 2015-08-25 21:07
Managed to package Let's Encrypt client using PyInstaller: https://github.com/letsencrypt/letsencrypt/pull/715 :)

**Comment by reaperhulk** [comment] 2015-10-22 04:06
Those who are working on doing this sort of thing: is there anything for cryptography to do here, or is it now a function of working with the tools to support entry points, etc?

**Comment by Repiklis** [comment] 2015-12-18 13:09
I know that this might not be they way forward, but it may help people for the time being.

I managed to package cryptography 1.1.2 with PyInstaller 3.0 by using @exvito 's patch_crypto_be_discovery routine. I added that in the hazmat\backends\__init__.py, and called it in the same file, at the _available_backends_list, which now looks like that:

    def _available_backends():
        global _available_backends_list

        if _available_backends_list is None:
            _available_backends_list = [
                # setuptools 11.3 deprecated support for the require parameter to
                # load(), and introduced the new resolve() method instead.
                # This can be removed if/when we can assume setuptools>=11.3. At
                # some point we may wish to add a warning, to push people along,
                # but at present this would result in too many warnings.
                ep.resolve() if hasattr(ep, "resolve") else ep.load(require=False)
                for ep in pkg_resources.iter_entry_points(
                    "cryptography.backends"
                )            
            ]

            if len(_available_backends_list) == 0:
                _available_backends_list = patch_crypto_be_discovery()

Additionally, I had to define cffi, cryptography.hazmat.backends.openssl and cryptography.fernet as hiddenimports in PyInstaller. These may vary though.

**Comment by pkoning2** [comment] 2016-01-08 16:57
I've run into issues here as well.  After some battles with py2exe, I dropped that and tried cx_freeze instead.  With that, I can get cryptography to work, but with limitations.

Specifically: I have to explicitly tell cx_freeze to include module "cffi".  Also, I can't use the default backend; I have to ask for a specific one (for example the openssl one).

Attached are a simple test program and the log from running it straight, then packaging it without then with the --include-modules=cffi switch.  Note that even with, the default_backend lookup does the wrong thing.

--paul


[ctest.py.txt](https://github.com/pyca/cryptography/files/82989/ctest.py.txt)
[ctest.log.txt](https://github.com/pyca/cryptography/files/82991/ctest.log.txt)

**Comment by nchammas** [comment] 2016-02-10 00:34
@reaperhulk

> Those who are working on doing this sort of thing: is there anything for cryptography to do here, or is it now a function of working with the tools to support entry points, etc?

In the case of PyInstaller support, I don't think there is anything for y'all to do here.

Cryptography-specific support for PyInstaller exists via [the Cryptography hook](https://github.com/pyinstaller/pyinstaller/blob/master/PyInstaller/hooks/hook-cryptography.py), and `entry_points` issues are being [tracked here](https://github.com/pyinstaller/pyinstaller/issues/1188).

**Comment by alex** [comment] 2016-03-05 15:48
Going to close this issue since it doesn't seem like there's anything cryptography itself should be doing here.

**Closed by alex** 2016-03-05 15:48 UTC

**Comment by Atheros1** [comment] 2016-05-11 21:18
Is cryptography supposed to be working with pyinstaller now? This code runs just fine in the terminal but not when packaged:

`import os
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.backends import default_backend

def AES_GCM_encrypt(key, plaintext):
    iv = os.urandom(12)
    print "default_backend():", default_backend()
    
    encryptor = Cipher(
        algorithms.AES(key),
        modes.GCM(iv),
        backend=default_backend()
    ).encryptor()
    
    ciphertext = encryptor.update(plaintext) + encryptor.finalize()
    return iv + encryptor.tag + ciphertext

key = os.urandom(32)
inData = os.urandom(1000000)
outData = AES_GCM_encrypt(key, inData)`

When packaged, it throws this:

`Traceback (most recent call last):
  File "<string>", line 20, in <module>
  File "<string>", line 7, in AES_GCM_encrypt
  File "site-packages\cryptography\hazmat\backends\__init__.py", line 35, in default_backend
  File "site-packages\cryptography\hazmat\backends\multibackend.py", line 33, in __init__
ValueError: Multibackend cannot be initialized with no backends. If you are seeing this error when trying to use default_backend() please try uninstalling and reinstalling cryptography.`

I'm using cryptography 1.3.1 and pyinstaller 3.1.1.    Thank you.

**Comment by reaperhulk** [comment] 2016-05-11 21:30
Cryptography uses entry points for backend discovery and pyinstaller may be having a problem with that (although that is only a guess). They've done some work in the past to support cryptography (https://github.com/pyinstaller/pyinstaller/issues/1425) but you should file an issue there if you are having problems.

**Comment by duarvor** [comment] 2016-05-20 14:58
Hello,
I had the same "ValueError: Multibackend cannot be initialized with no backends." with cx_freeze
so, I put the folder "cryptography-1.3.2.dist-info" (not zipped in the build folder)  witch contains "entry_points.txt"
```
[cryptography.backends]
openssl = cryptography.hazmat.backends.openssl:backend
```
and cryptography run now fine like in the terminal.

**Comment by markw63** [comment] 2016-06-28 11:35
```
To put that all together.. This is the replacement hazmat/backends/__init__.py
# This file is dual licensed under the terms of the Apache License, Version
# 2.0, and the BSD License. See the LICENSE file in the root of this repository
# for complete details.

from __future__ import absolute_import, division, print_function

import pkg_resources

from cryptography.hazmat.backends.multibackend import MultiBackend


_available_backends_list = None
def patch_crypto_be_discovery():
    
    """
        Monkey patches cryptography's backend detection.
        Objective: support pyinstaller freezing.
        """
    
    from cryptography.hazmat import backends
    
    try:
        from cryptography.hazmat.backends.commoncrypto.backend import backend as be_cc
    except ImportError:
        be_cc = None
    
    try:
        from cryptography.hazmat.backends.openssl.backend import backend as be_ossl
    except ImportError:
        be_ossl = None
    
    backends._available_backends_list = [
        be for be in (be_cc, be_ossl) if be is not None
         ]

def _available_backends():
    global _available_backends_list

    if _available_backends_list is None:
        _available_backends_list = [
            # setuptools 11.3 deprecated support for the require parameter to
            # load(), and introduced the new resolve() method instead.
            # This can be removed if/when we can assume setuptools>=11.3. At
            # some point we may wish to add a warning, to push people along,
            # but at present this would result in too many warnings.
            ep.resolve() if hasattr(ep, "resolve") else ep.load(require=False)
            for ep in pkg_resources.iter_entry_points(
                "cryptography.backends"
            )
        ]
        if len(_available_backends_list) == 0:
            _available_backends_list = patch_crypto_be_discovery()
    return _available_backends_list

_default_backend = None


def default_backend():
    global _default_backend

    if _default_backend is None:
        _default_backend = MultiBackend(_available_backends())

    return _default_backend


```

**Comment by pablo-esteban** [comment] 2016-07-18 16:12
Hello all,

Unfortunately, version 1.4 of cryptography does not work with py2exe 0.6.9. I have even modified `hazmat/backends/__init__.py` to match the comment above. Here is a minimal example:

    import sys

    from cryptography.fernet import Fernet


    if __name__ == '__main__':
        command = sys.argv[1]
        message = sys.argv[2]
        key = sys.argv[3]
        
        f = Fernet(key)
        
        if command == 'encrypt':
            token = f.encrypt(message)
            print token
        elif command == 'decrypt':
            print f.decrypt(message)
        else:
            print 'Unrecognised command'
            
        exit()

This is my setup.py file for py2exe:

    from distutils.core import setup
    import py2exe

    setup(
        name='Mini Crypto Codec',
        options={
            'py2exe': {
                'packages': ['cryptography'],
            }
        },
        zipfile='lib/library.zip',
        windows=[
            {'script': 'minicryptocodec/main.py',
             'dest_base': 'cryptocodec'
            }
        ],
    )

The executable is successfully created, but when you attempt to run it this error occurrs:

    Traceback (most recent call last):
      File "main.py", line 3, in <module>
      File "cryptography\fernet.pyc", line 16, in <module>
      File "cryptography\hazmat\backends\__init__.pyc", line 7, in <module>
      File "pkg_resources\__init__.pyc", line 68, in <module>
      File "pkg_resources\extern\__init__.pyc", line 60, in load_module
    ImportError: The 'packaging' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.

I'm running this on Windows 7 with Python 2.7.12 (32bit) and py2exe 0.6.9

**Comment by stephenrauch** [comment] 2016-08-30 16:29
FYI, just submitted a [PR with a pyinstaller hook](https://github.com/pyinstaller/pyinstaller/pull/2167) which resolves:

```
ValueError: Multibackend cannot be initialized with no backends. If you are seeing this error when trying to use default_backend() please try uninstalling and reinstalling cryptography.
```

**Comment by aristotle23** [comment] 2016-12-05 10:41
using the patch throws me TypeError : object of type "NoneType" have no len()

**Comment by reaperhulk** [comment] 2016-12-05 13:44
No patches should be required as of version 1.6. See #3235
